### ISSUE TITLE
[BUG] Private key generated not 32 bytes. 

### ISSUE THREAD

**Issue by c98tristan** [sei-protocol/sei-chain#1003]
**Seid version**
    name: sei
    server_name: <appd>
    version: 3.0.6-17-g31465d70
    commit: 31465d70e91e9059fe786e25c5973c8beed154e1
    build_tags: netgo,ledger
    go: go version go1.20.6 darwin/arm64
    build_deps:
    - filippo.io/edwards25519@v1.0.0-beta.2
    - github.com/99designs/keyring@v1.1.6
    - github.com/CosmWasm/wasmd@v0.27.0 => github.com/sei-protocol/sei-wasmd@v0.0.2
**Chain ID**
atlantic-2

**Describe the bug**
I export the private key with: `seid keys export tri --unarmored-hex --unsafe`
I got an string with 37 bytes. I expect an 32 bytes private key.

**To Reproduce**
1. `seid keys add abc`
2. `seid keys export abc --unarmored-hex --unsafe`

**Expected behavior**
32 Bytes private key

**Screenshots**
![image](https://github.com/sei-protocol/sei-chain/assets/134263124/c02eede2-1fd3-467c-aba4-808053367527)

**Comment by alexanderbez** [comment]
So Sei has a Cosmos SDK fork based off of v0.45.x. There are a few changes to the keyring package. Specific to this context, the major difference I see is that:

* The SDK performs a `hex.EncodeToString(priv.Bytes())`, where `priv` is a  `types.PrivKey` type.
* The Sei SDK fork performs a `hex.EncodeToString(priv)`, where `priv` is a `[]byte` type, which comes from `legacy.Cdc.MustMarshal(privKeys)`

My guess is that Sei SDK fork should just call/return `priv.Bytes` instead of calling `legacy.Cdc.MustMarshal`

**Comment by seungjulee** [comment]
Based on @alexanderbez investigation, I think that we need to modify these lines of code.

Sei Cosmos
https://github.com/sei-protocol/sei-cosmos/blob/main/crypto/keyring/keyring.go#L252

Diff on Cosmos SDK: https://github.com/cosmos/cosmos-sdk/pull/9695/files#diff-6832e2d710aed661f9b5941a88ac18045bb2555d7d9be1319f403dbe928017b4R240
(link doesn't go to the line. search for keyring.go and `ExportPrivateKeyObject`)

**Comment by seungjulee** [comment]
I tried to make a [one liner change](https://github.com/seungjulee/sei-cosmos/commit/41031dbbbfcf2d928ac7adf91829d216ab67ca23) as suggested by @alexanderbez

But the existing tests and implementation fail, and the solution needs more investigation. 

Specifically functions like `keystore.Sign()` uses [`legacy.Unmarshall`](https://github.com/sei-protocol/sei-cosmos/blob/main/codec/legacy/codec.go#L22) to create `types.PrivKey` from   `PrivKeyFromBytes` call. Before it was outputting  37 bytes, but now that it's returning 32 bytes, the unmarshaller can't unmarshal raw 32 bytes private key with an error saying  `unmarshal to types.PrivKey failed after 4 byte`. We need a solution that works for both marshalling and unmarshalling. 

I think the proper way to fix this would be merging in keyring changes from cosmo-sdk which removes the legacy cdc. Alternatively we can fix the original issue from legacy cdc amino unmarshal. 

It looks like this has been outputting 37 bytes for a while in cosmos-sdk until v0.45x. Even [this test](https://github.com/sei-protocol/sei-cosmos/blob/main/crypto/keyring/keyring_test.go#L898) was written to expect 37 bytes (74 = 37*2), and was [later changed](https://github.com/cosmos/cosmos-sdk/blob/main/crypto/keyring/keyring_test.go#L1006C23-L1006C63) to expect 32 bytes (64 = 32*2)

**Comment by philipsu522** [comment]
we will close this out for now until we merge in cosmos sdk changes. thanks for the report!
