### ISSUE TITLE
seid cannot add keys using `os` keyring backend

### ISSUE THREAD

**Issue by Soptq** [sei-protocol/sei-chain#101]
Command:
```
seid keys add test
```
Outputs:
```
Error: Object does not exist at path “/”
Usage:
  seid keys add <name> [flags]
```

Two observations:
1. `--dry-run` works.
2. switch keyring-backend to `file` works.

seid version: 
```
1.0.6beta
```
os: 
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```

**Comment by mturkia** [comment]
This is probably an issue with the keyring configuration of the OS. (Works fine for me with OS backend.)

**Comment by philipsu522** [comment]
Yep, feel free to try again if you're having issues. Your os backedn seems misconfigured.

**Comment by Condechat** [comment]
i think this line is missing (works for my case)
#chain  config keyring-backend file
