### ISSUE TITLE
Is there a complete rpc list? (including parameter meaning)

### ISSUE THREAD

**Issue by 1921Aaron** [sei-protocol/sei-chain#1012]
### Search before asking

- [X] I searched in the [issues](https://github.com/sei-protocol/sei-chain/issues) and found nothing similar.

### Motivation

I'm working on an integration for our exchange, but can't find a complete rpc doc

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lukfm-mms** [comment]
Hi man! 
feel free to use=)
https://rpc-sei-testnet.mms.team
https://api-sei-testnet.mms.team
https://grpc-sei-testnet.mms.team

**Comment by lukfm-mms** [comment]
I agree with the idea of ​​creating complete rpc doc

**Comment by yzang2019** [comment]
We will release the doc for complete rpc soon

**Comment by philipsu522** [comment]
https://docs.sei.io/develop/resources

**Comment by jayjacklin** [comment]
> 我们将很快发布完整的rpc文档
Do you have a specific time plan?
