### ISSUE TITLE
[BUG] Can't install seid following documentation

### ISSUE THREAD

**Issue by vlbhtcno1** [sei-protocol/sei-chain#1013]
![image](https://github.com/sei-protocol/sei-chain/assets/15800163/5dde0374-a819-4b80-b001-7c69b01120e5)

**Comment by yzang2019** [comment]
@vlbhtcno1 can you check where your go path is? It seems that you need to configure your go bin path correctly for your system PATH.

Try something like:
go env
export PATH=$PATH:/usr/local/go/bin

**Comment by chenjie1219** [comment]
+1
