### ISSUE TITLE
[Error] bridge ETH>sei failure (loss 0.07 eth)

### ISSUE THREAD

**Issue by snipeTR** [sei-protocol/sei-chain#1015]
I tried to perform a bridge operation from ETH to SEI. However, while testing, I attempted to 'speed up' the 0.07 ETH transaction I sent, without waiting for its confirmation. As a result, I encountered the following error message. I am providing the relevant ETH Gorli transaction ID and the error message from the site.

NOTE: I have experienced issues with Wormhole on another network before. Wormhole does not take responsibility for the transactions and does not refund the stuck values if the transaction fails to go through. The money disappears. Please avoid using Wormhole.

https://goerli.etherscan.io/tx/0x4312d988be7f1619e8b8065f4e303b03ddca3b7d657de46d7fd16fb0d13d439c
destination sei address
sei1yakd4kq7cnftpuy3psyrmep0vggax0pc909cvt

`Error: transaction was replaced [ See: https://links.ethers.org/v5-errors-TRANSACTION_REPLACED ] (cancelled=false, reason="repriced", replacement={"hash":"0x4312d988be7f1619e8b8065f4e303b03ddca3b7d657de46d7fd16fb0d13d439c","type":2,"accessList":[],"blockHash":"0x20533c691afa768fc3568316fd1ddf6f4b6ed230ad102777e745fb98e4c863fe","blockNumber":9471149,"transactionIndex":13,"confirmations":1,"from":"0x99553E079B5dCf9e14970B08A193616624e70618","gasPrice":{"type":"BigNumber","hex":"0x62590094"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x62590080"},"maxFeePerGas":{"type":"BigNumber","hex":"0x625900a4"},"gasLimit":{"type":"BigNumber","hex":"0x015330"},"to":"0xF890982f9310df57d00f659cf4fd87e65adEd8d7","value":{"type":"BigNumber","hex":"0xf8b0a10e470000"},"nonce":236,"data":"0xbee9cdfc00000000000000000000000000000000000000000000000000000000000000206d9ae6b2d333c1d65301a59da3eed388ca5dc60cb12496584b75cbe6b15fdbed00000000000000000000000000000000000000000000000000000000317b00000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000005c7b2262617369635f726563697069656e74223a7b22726563697069656e74223a22633256704d586c6861325130613345335932356d6448423165544e7763336c79625756774d485a6e5a3246344d48426a4f54413559335a30227d7d00000000","r":"0xbbc4202a726d6b2df4990db72996bc856db5081eb7bab4652663656d658e5ee0","s":"0x7a4e705ec8a54cc5319a195dc53cfe28b3aa2bd891c630d5028eb1f15a313f2c","v":0,"creates":null,"chainId":5}, hash="0x70207867821f788abd91b4d3f78ebc782ab372a8208a346f2d2409f63cfd0ccb", receipt={"to":"0xF890982f9310df57d00f659cf4fd87e65adEd8d7","from":"0x99553E079B5dCf9e14970B08A193616624e70618","contractAddress":null,"transactionIndex":13,"gasUsed":{"type":"BigNumber","hex":"0x014fcb"},"logsBloom":"0x00000000000100000000000000000000000000000000000000000000000000000010000000000000000001000000000000000000000000000000020002000000000000000400000000000000000000000000000000000000000200008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000400000000000000000040000400000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000400000000000000000","blockHash":"0x20533c691afa768fc3568316fd1ddf6f4b6ed230ad102777e745fb98e4c863fe","transactionHash":"0x4312d988be7f1619e8b8065f4e303b03ddca3b7d657de46d7fd16fb0d13d439c","logs":[{"transactionIndex":13,"blockNumber":9471149,"transactionHash":"0x4312d988be7f1619e8b8065f4e303b03ddca3b7d657de46d7fd16fb0d13d439c","address":"0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6","topics":["0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c","0x000000000000000000000000f890982f9310df57d00f659cf4fd87e65aded8d7"],"data":"0x00000000000000000000000000000000000000000000000000f8b0a10e470000","logIndex":19,"blockHash":"0x20533c691afa768fc3568316fd1ddf6f4b6ed230ad102777e745fb98e4c863fe"},{"transactionIndex":13,"blockNumber":9471149,"transactionHash":"0x4312d988be7f1619e8b8065f4e303b03ddca3b7d657de46d7fd16fb0d13d439c","address":"0x706abc4E45D419950511e474C7B9Ed348A4a716c","topics":["0x6eb224fb001ed210e379b335e35efe88672a8ce935d981a6896b27ffdf52a3b2","0x000000000000000000000000f890982f9310df57d00f659cf4fd87e65aded8d7"],"data":"0x000000000000000000000000000000000000000000000000000000000002802d00000000000000000000000000000000000000000000000000000000317b00000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000e10300000000000000000000000000000000000000000000000000000000006acfc0000000000000000000000000b4fbf271143f4fbf7b91a5ded31805e42b2208d600026d9ae6b2d333c1d65301a59da3eed388ca5dc60cb12496584b75cbe6b15fdbed002000000000000000000000000099553e079b5dcf9e14970b08a193616624e706187b2262617369635f726563697069656e74223a7b22726563697069656e74223a22633256704d586c6861325130613345335932356d6448423165544e7763336c79625756774d485a6e5a3246344d48426a4f54413559335a30227d7d00000000000000000000000000000000000000000000000000000000000000","logIndex":20,"blockHash":"0x20533c691afa768fc3568316fd1ddf6f4b6ed230ad102777e745fb98e4c863fe"}],"blockNumber":9471149,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x159ca5"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x62590094"},"status":1,"type":2,"byzantium":true}, code=TRANSACTION_REPLACED, version=providers/5.7.2)`

**Comment by LCyson** [comment]
which UI did you use to bridge fund from ETH to SEI ser?

**Comment by LCyson** [comment]
and to confirm you're not seeing the 0.07ETH you were trying to bridge from ETH to SEI in your sei wallet: https://www.seiscan.app/atlantic-2/accounts/sei1yakd4kq7cnftpuy3psyrmep0vggax0pc909cvt 
we checked the tx and it was successfully bridged. The weth denom on atlantic-2 is `factory/sei1dkdwdvknx0qav5cp5kw68mkn3r99m3svkyjfvkztwh97dv2lm0ksj6xrak/AAxKX63hpBQrGGf6uhB21dJuXupvHxNTHJaktAETVGh6` (the explorer will update it to human-readable asset soon)

**Comment by luksbit** [comment]
Is the SEI bridge to eth - Goerli being executed ? 

Error: Error when broadcasting tx BA1B94DBDD0A24F6CA11D7A2B95AA2D5805CFE1644F4234D73FA4FA3468ACC4B at height 27903587. Code: 29; Raw log: failed to execute message; message index: 0: dispatch: submessages: dispatch: submessages: dispatch: submessages: cannot send packet using client (07-tendermint-55) with status Expired: client is not active

**Comment by philipsu522** [comment]
> Is the SEI bridge to eth - Goerli being executed ?
> 
> Error: Error when broadcasting tx BA1B94DBDD0A24F6CA11D7A2B95AA2D5805CFE1644F4234D73FA4FA3468ACC4B at height 27903587. Code: 29; Raw log: failed to execute message; message index: 0: dispatch: submessages: dispatch: submessages: dispatch: submessages: cannot send packet using client (07-tendermint-55) with status Expired: client is not active

It should be up and running, can you retry

Also for the original issue, it was a UI bug which resulted in speeding up txs that has since been fixed. The tx didn't fail, if you query the chain you'll see it succeeded.

**Comment by luksbit** [comment]
oks ... Thanks
