### ISSUE TITLE
could not use peer for statesync (removing)

### ISSUE THREAD

**Issue by Jackwumingjie** [sei-protocol/sei-chain#1025]
**Seid version**
name: sei
server_name: <appd>
version: 3.0.8
commit: 605ce0378a0429f04032f095e64ddca014a7128b
build_tags: netgo,ledger
go: go version go1.21.0 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6
- github.com/CosmWasm/wasmd@v0.27.0 => github.com/sei-protocol/sei-wasmd@v0.0.2

**Chain ID**
pacific-1

**Describe the bug**
The node can't sync as the picture
<img width="1439" alt="image" src="https://github.com/sei-protocol/sei-chain/assets/39093109/2b02d03e-7640-4069-9fdb-6258e809900c">

**To Reproduce**
1. make install
2. seid init
3.  add the seeds='ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:11956' to the config.toml
4. seid start

**Expected behavior**
can sync normally

**Screenshots**
<img width="1432" alt="image" src="https://github.com/sei-protocol/sei-chain/assets/39093109/ba23eda3-4f91-4a14-9efd-898ac88475dc">

**Additional context**
refer doc: https://polkachu.com/installation/sei

**Comment by yzang2019** [comment]
@Jackwumingjie Can you follow this https://docs.sei.io/full-node/run-a-sei-node for state sync, and there should be a list of state sync providers you can choose from
