### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by ratneshpatil-rp** [sei-protocol/sei-chain#1027]
Hi Team,

after cloning the solution, During "Make Install" we are getting error- 
go install -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=sei -X github.com/cosmos/cosmos-sdk/version.ServerName=seid -X github.com/cosmos/cosmos-sdk/version.Version=2.0.47 -X github.com/cosmos/cosmos-sdk/version.Commit=a7995cab1b0f15162665fb2afd16e28105c6b90b -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/seid
/bin/sh: 1: go: not found
make: *** [Makefile:68: install] Error 127

also Can send us the Steps to Set-up node

**Comment by felipepimsil** [comment]
`/bin/sh: 1: go: not found`
You need to install `go`. `seid` requires 1.18+ version. Install it and add it to the $PATH and verify it with:
`$ go version`

**Comment by yzang2019** [comment]
Correct, @ratneshpatil-rp you need to configure and install go correctly. For the sei document, you can refer to https://docs.sei.io/, there's instructions for how to set up local sei node, or running sei on local docker cluster

**Comment by ratneshpatil-rp** [comment]
We are trying to set node for atlantic 2.
can you send peers list.

Also we ran this command to start node- sudo docker run -d -it -p 8332:26657  -p 7332:1317 -v /SEIDisk/node-SEI/SEI/.sei:/SEI/.sei sei:latest seid start  --pruning nothing --home /SEI/.sei --chain-id atlantic-2

but it said ChainId not matching in config.toml and genesis.

Genesis- https://[raw.githubusercontent.com/sei-protocol/testnet/master/atlantic-2/genesis.json](https://raw.githubusercontent.com/sei-protocol/testnet/master/atlantic-2/genesis.json)

**Comment by MrCrazid** [comment]
> `/bin/sh: 1: go: not found`
> 
> 
> 
> You need to install `go`. 
> 
> `seid` requires 1.18+ `go` version. Install it and add it to the $PATH and verify it with:
> 
> `$ go version`

I don't quite understand what you're saying but if you could put it into laymen's terms that would be great appreciate

**Comment by MrCrazid** [comment]
> We are trying to set node for atlantic 2.
> 
> can you send peers list.
> 
> 
> 
> Also we ran this command to start node- sudo docker run -d -it -p 8332:26657  -p 7332:1317 -v /SEIDisk/node-SEI/SEI/.sei:/SEI/.sei sei:latest seid start  --pruning nothing --home /SEI/.sei --chain-id atlantic-2
> 
> 
> 
> but it said ChainId not matching in config.toml and genesis.
> 
> 
> 
> Genesis- https://[raw.githubusercontent.com/sei-protocol/testnet/master/atlantic-2/genesis.json](https://raw.githubusercontent.com/sei-protocol/testnet/master/atlantic-2/genesis.json)

**Comment by MrCrazid** [comment]
Ok I have the original block chain numbers and any other information or proof that you may need. If you could kindly provide me with a list of everything that you need to straighten this all out that would be greatly helpful and would really help me out in understanding what you are looking for et

**Comment by ratneshpatil-rp** [comment]
Hi @MrCrazid ,

We are trying to set-up a node to have balance and transactions and blockinfo.
We have a idea cosmos set-up

Steps we followed.
1) git clone https://github.com/sei-protocol/sei-chain/tree/main

2) sudo docker build -t sei:latest .

3) we get images. 

4) Run -- sudo docker run -it -p 26657:26657 -p 26656:26656 -v /SEIDisk/node-SEI/SEI/.sei:/sei/.sei sei:atlantis2 seid init sei --chain-id atlantis2

5) we get .sei, in that config and data. In that added Genesis.json from https://[raw.githubusercontent.com/sei-protocol/testnet/master/atlantic-2/genesis.json](https://raw.githubusercontent.com/sei-protocol/testnet/master/atlantic-2/genesis.json)

6) no change in config.toml

7) sudo docker run -d -it -p 26657:26657 -p 26656:26656 -v /SEIDisk/node-SEI/SEI/.sei:/SEI/.sei sei:latest seid start --pruning nothing --home /SEI/.sei --chain-id atlantic-2

We are gettting error
Error -panic: runtime error: invalid memory address or nil pointer dereference

Can you send Peers List and Seeds

**Comment by ratneshpatil-rp** [comment]
@MrCrazid , @felipepimsil  any update?

**Comment by qezz** [comment]
@ratneshpatil-rp chain id is `atlantic-2`, not `atlantis2`

**Comment by ratneshpatil-rp** [comment]
So we did git clone git clone https://github.com/sei-protocol/sei-chain/tree/main

Git checkout 3.0.8

then make build is giving error

![IMG_6120](https://github.com/sei-protocol/sei-chain/assets/67742942/f59f7ed0-c32d-47dd-85ec-fbfaf55be31e)

also we followed the documentation after that we are getting

![Uploading IMG_6119.png…]()

**Comment by philipsu522** [comment]
> So we did git clone git clone https://github.com/sei-protocol/sei-chain/tree/main
> 
> Git checkout 3.0.8
> 
> then make build is giving error
> 
> ![IMG_6120](https://user-images.githubusercontent.com/67742942/262720529-f59f7ed0-c32d-47dd-85ec-fbfaf55be31e.jpeg)
> 
> also we followed the documentation https://brocha.in/testnet/sei-testnet-2/installation after that we are getting
> 
> Error: exit status 1 3:30PM ERR error="exit status 1" module=cosmovisor seid.service: Main process exited, code=exited, status=1/FAILURE seid.service: Failed with result 'exit-code'. seid.service: Scheduled restart job, restart counter is at 1908. Stopped Sei Atlantic 2 Node Service. Started Sei Atlantic 2 Node Service. 3:30PM INF running app args=["start"] module=cosmovisor path=/home/coiniaadmin/.sei/cosmovisor/upgrades/3.0.8/bin/seid 3:30PM INF --tracing not passed in, tracing is not enabled 3:30PM INF Creating node metrics provider 3:30PM INF Starting Process failed to load latest version: failed to load store: Value missing for hash 189b5d40ebb8ebe72f7a7567d0d71f408d835eed199641d6f9c50b741a6f1890 corresponding to nodeKey 6e189b5d40ebb8ebe72f7a7567d0d71f408d835eed199641d6f9c50b741a6f1890 Error: exit status 1 3:30PM ERR error="exit status 1" module=cosmovisor seid.service: Main process exited, code=exited, status=1/FAILURE seid.service: Failed with result 'exit-code'. seid.service: Scheduled restart job, restart counter is at 1909. Stopped Sei Atlantic 2 Node Service. Started Sei Atlantic 2 Node Service. 3:30PM INF running app args=["start"] module=cosmovisor path=/home/coiniaadmin/.sei/cosmovisor/upgrades/3.0.8/bin/seid 3:30PM INF --tracing not passed in, tracing is not enabled 3:30PM INF Creating node metrics provider 3:30PM INF Starting Process failed to load latest version: failed to load store: Value missing for hash 403b57482a06fdd8520c6f7bb3bc03d4a513fe80b97cefbf20b92575543dea87 corresponding to nodeKey 6e403b57482a06fdd8520c6f7bb3bc03d4a513fe80b97cefbf20b92575543dea87 Error: exit status 1 3:30PM ERR error="exit status 1" module=cosmovisor seid.service: Main process exited, code=exited, status=1/FAILURE seid.service: Failed with result 'exit-code'.

looks like you have some bad state in your $HOME/.sei directory from multiple restarts. Can you wipe it and retry

**Comment by ratneshpatil-rp** [comment]
Hi Team,

root@COINIANPDUBUNTU1:/NewDisk44Machine/node-sei/sei/sei-chain# go version
go version go1.19.4 linux/amd64
root@COINIANPDUBUNTU1:/NewDisk44Machine/node-sei/sei/sei-chain# sudo make install
fatal: detected dubious ownership in repository at '/NewDisk44Machine/node-sei/sei/sei-chain'
To add an exception for this directory, call:

        git config --global --add safe.directory /NewDisk44Machine/node-sei/sei/sei-chain
fatal: detected dubious ownership in repository at '/NewDisk44Machine/node-sei/sei/sei-chain'
To add an exception for this directory, call:

        git config --global --add safe.directory /NewDisk44Machine/node-sei/sei/sei-chain
go install -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=sei -X github.com/cosmos/cosmos-sdk/version.ServerName=seid -X github.com/cosmos/cosmos-sdk/version.Version= -X github.com/cosmos/cosmos-sdk/version.Commit= -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/seid
fatal: detected dubious ownership in repository at '/NewDisk44Machine/node-sei/sei/sei-chain'
To add an exception for this directory, call:

        git config --global --add safe.directory /NewDisk44Machine/node-sei/sei/sei-chain
/bin/sh: 1: go: not found
make: *** [Makefile:69: install] Error 127
root@COINIANPDUBUNTU1:/NewDisk44Machine/node-sei/sei/sei-chain# make install
go install -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=sei -X github.com/cosmos/cosmos-sdk/version.ServerName=seid -X github.com/cosmos/cosmos-sdk/version.Version=3.0.8 -X github.com/cosmos/cosmos-sdk/version.Commit=605ce0378a0429f04032f095e64ddca014a7128b -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/seid
go: downloading github.com/sei-protocol/sei-cosmos v0.2.61
go: downloading github.com/sei-protocol/sei-wasmd v0.0.2
go: downloading github.com/sei-protocol/sei-ibc-go/v3 v3.1.0
go: downloading github.com/spf13/cast v1.5.0
go: downloading github.com/stretchr/testify v1.8.4
go: downloading github.com/sei-protocol/sei-tendermint v0.2.25
go: downloading github.com/sei-protocol/tm-db v0.0.4
go: downloading go.opentelemetry.io/otel v1.9.0
go: downloading github.com/sei-protocol/sei-iavl v0.1.7
go: downloading github.com/spf13/cobra v1.5.0
go: downloading github.com/syndtr/goleveldb v1.0.1-0.20210819022825-2ae1ddf74ef7
go: downloading github.com/CosmWasm/wasmvm v1.0.1
go: downloading github.com/armon/go-metrics v0.4.0
go: downloading github.com/prometheus/client_golang v1.12.2
go: downloading github.com/golang/protobuf v1.5.3
go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20230530153820-e85fd2cbaebc
go: downloading github.com/spf13/viper v1.13.0
go: downloading github.com/sei-protocol/sei-tm-db v0.0.5
go: downloading google.golang.org/genproto v0.0.0-20230526203410-71b5a4ffd15e
go: downloading go.opentelemetry.io/otel/trace v1.9.0
go: downloading github.com/cosmos/cosmos-sdk/ics23/go v0.8.0
go: downloading github.com/hashicorp/golang-lru/v2 v2.0.1
go: downloading github.com/hashicorp/golang-lru v0.5.5-0.20210104140557-80c98217689d
go: downloading golang.org/x/exp v0.0.0-20221031165847-c99f073a8326
go: downloading go.opentelemetry.io/otel/exporters/jaeger v1.9.0
go: downloading go.opentelemetry.io/otel/sdk v1.9.0
go: downloading github.com/savaki/jq v0.0.0-20161209013833-0e6baecebbf8
go: downloading github.com/yourbasic/graph v0.0.0-20210606180040-8ecfec1c2869
go: downloading github.com/deckarep/golang-set v1.8.0
go: downloading google.golang.org/protobuf v1.30.0
go: downloading github.com/sei-protocol/goutils v0.0.2
go: downloading golang.org/x/text v0.9.0
go: downloading github.com/go-kit/log v0.2.1
go: downloading github.com/rs/zerolog v1.27.0
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading golang.org/x/crypto v0.1.0
go: downloading github.com/google/btree v1.1.2
go: downloading github.com/prometheus/common v0.34.0
go: downloading github.com/oasisprotocol/curve25519-voi v0.0.0-20210609091139-0a56a4bca00b
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20230530153820-e85fd2cbaebc
go: downloading golang.org/x/net v0.10.0
go: downloading github.com/fsnotify/fsnotify v1.5.4
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/felixge/httpsnoop v1.0.2
go: downloading github.com/btcsuite/btcd v0.22.1
go: downloading golang.org/x/sys v0.8.0
go: downloading github.com/libp2p/go-buffer-pool v0.1.0
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/lib/pq v1.10.6
go: downloading github.com/subosito/gotenv v1.4.1
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/pelletier/go-toml/v2 v2.0.5
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/pelletier/go-toml v1.9.5
go: downloading golang.org/x/term v0.8.0
go: downloading golang.org/x/sync v0.1.0
go: downloading github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
go: downloading github.com/creachadair/taskgroup v0.3.2
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/klauspost/compress v1.15.9
root@COINIANPDUBUNTU1:/NewDisk44Machine/node-sei/sei/sei-chain# -chain-id "" "$MONIKER"
-chain-id: command not found
root@COINIANPDUBUNTU1:/NewDisk44Machine/node-sei/sei/sei-chain# export VERSION=3.0.9
root@COINIANPDUBUNTU1:/NewDisk44Machine/node-sei/sei/sei-chain# export CHAIN_ID="atlantic-2"
root@COINIANPDUBUNTU1:/NewDisk44Machine/node-sei/sei/sei-chain# export MONIKER="sei"
root@COINIANPDUBUNTU1:/NewDisk44Machine/node-sei/sei/sei-chain# seid init --chain-id "$CHAIN_ID" "$MONIKER"

Command 'seid' not found, did you mean:

  command 'ssid' from deb suckless-tools (44-1)
  command 'sed' from deb sed (4.7-1)
  command 'sxid' from deb sxid (4.20130802-1ubuntu2)
  command 'eid' from deb id-utils (4.6+git20120811-4ubuntu2)
  command 'scid' from deb scid (1:4.7.0+dfsg1-1ubuntu2)
  command 'send' from deb mailutils-mh (1:3.7-2.1)
  command 'send' from deb mmh (0.4-2)
  command 'send' from deb nmh (1.7.1-6)

Try: apt install <deb name>


still seid not command
can you check once

**Comment by philipsu522** [comment]
Seems like you got seid working in another issue. Closing
