### ISSUE TITLE
Exporting mnemonics in a Linux environment

### ISSUE THREAD

**Issue by onebyoneby** [sei-protocol/sei-chain#1028]
How to export mnemonics using the seid command in a Linux environment? I have checked the command and found that importing and exporting files only have the form of a secret key. I want to export files in the form of a key or mnemonic and then import them into a webpage to import a wallet

![image](https://github.com/sei-protocol/sei-chain/assets/50565415/66cf2519-3b96-4d45-a8be-8fe7f04067ab)

**Comment by onebyoneby** [comment]
And each interaction requires entering a password. How can I close it!

**Comment by onebyoneby** [comment]
I am very sorry that I still have another question. I am writing a webpage debugging wallet, how to get the gas fee request required for the transaction, and I have set a fixed gas fee at present

**Comment by yzang2019** [comment]
> And each interaction requires entering a password. How can I close it!

You can use --keyring-backend test to skip the password

**Comment by yzang2019** [comment]
I'm not sure whether we support exporting mnemonics, that's something generated only once and can't be exported later, so you would have to save it somehow when you create a new wallet.

We do support exporting the secret key which can be used to recover the account.
