### ISSUE TITLE
[BUG] Data Not Matching with explorer

### ISSUE THREAD

**Issue by ratneshpatil-rp** [sei-protocol/sei-chain#1035]
**Seid version**
3.0.8

**Chain ID**
Pacific-2

**Describe the bug**
We set-up a docker make after cloning the code. command - sudo make docker-cluster-start
node started we got the response also. But checked the blockhash for a particular block its not matching the explorer.
Even blocktime not matching.

**To Reproduce**
1. git pull https://github.com/sei-protocol/sei-chain
2. in sei-chain-   make docker-cluster-start
3. curl --location --request GET 'http://localhost:26657/block'

**Expected behavior**
to set-up sei chain for pacific1 mainnet to fetch transaction and balance data. it should match explorer

**Screenshots**
 curl --location --request GET 'http://10.213.72.23:26657/block'
{"block_id":{"hash":"9032F604DAC2FF9D9095B2E9577A5A04FE7108D3D47C31F83C5D6679C78E52C8","parts":{"total":1,"hash":"9E03A2131EE30C0488DC282763581719F5DF4E617BB3D7507EE5D0CC7C76CC96"}},"block":{"header":{"version":{"block":"11","app":"0"},"chain_id":"sei","height":"18119","time":"2023-08-25T12:53:11.009710155Z","last_block_id":{"hash":"A556CD06595F9B4ED2B75AF97A6243F7C0C673C922848BB5A98456A56401D592","parts":{"total":1,"hash":"5022FAD766DDBA0AAC3BA66E15771DD11BEA58C6BD03EDCC285751102B14E02A"}}

blockhash is F9D3845DF25B43B1C6926F3CEDA6845C17F5624E12212FD8847D0BA01DA1AB9E

explorer for blockheight=

**Additional context**
can you also tell where the data gets store?. 
if this is local set-up, how can we set-up a node to get info for pacific1 from docker image?
Or do you have archieval snapshot?

**Comment by yzang2019** [comment]
1. There's no chain-id called pacific-2, I assume you are talking about pacific-1
2. The docker chain that you launched and tested is a local chain, because it runs a separate validators, even if you use the same chain-id, everything is still independent, it's different sei mainnet. So it is expected that you won't find any transaction from you local chain that matches with the transaction in our mainnet. Local chain data are stored on your local laptop
3. Which explorer are you using? Please provide a link
4. If you want to run a full node for pacific-1 to get real transaction data, you need to do state sync, please follow this guide: https://docs.sei.io/full-node/run-a-sei-node

**Comment by ratneshpatil-rp** [comment]
https://docs.sei.io/full-node/run-a-sei-node
when follow this steps after make install 
getting this error
coiniaadmin@COINIANPDUBUNTU1:/NewDisk44Machine/node-sei/sei/sei-chain$ sudo make install
go install -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=sei -X github.com/cosmos/cosmos-sdk/version.ServerName=seid -X github.com/cosmos/cosmos-sdk/version.Version=3.0.8 -X github.com/cosmos/cosmos-sdk/version.Commit=605ce0378a0429f04032f095e64ddca014a7128b -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/seid
/bin/sh: 1: go: not found
make: *** [Makefile:69: install] Error 127


is there any arhcieval snapshot for Pacific-1, peerslist and seeds.

**Comment by yzang2019** [comment]
This means your haven't correctly configure your go bin PATH. Please export go to your PATH environment first and make sure `go env` and `go version` works

**Comment by ratneshpatil-rp** [comment]
I followed https://polkachu.com/installation/sei

should we download snapshot?

and without snapshot

gettting following logs

root@COINIANPDUBUNTU1:/NewDisk44Machine/node-sei/sei/sei-chain# sudo journalctl -fu sei
-- Logs begin at Wed 2023-05-17 23:32:11 UTC. --

**Comment by ratneshpatil-rp** [comment]
any update? why?

**Comment by ratneshpatil-rp** [comment]
Hi Team,

We followed the https://brocha.in/sei/installation.

Now we are getting logs:
ice=MConnection
7:35AM INF peer connected endpoint={} module=p2p peer=20e1000e88125698264454a884812746c2eb4807
7:35AM ERR could not use peer for statesync (removing) module=statesync peer=20e1000e88125698264454a884812746c2eb4807
7:35AM ERR could not use peer for dbsync (removing) module=dbsync peer=20e1000e88125698264454a884812746c2eb4807
7:35AM ERR failed to send request for peers err="no available peers to send a PEX request to (retrying)"
7:35AM INF stopping service module=p2p peer={"Hostname":"65.108.227.217","NodeID":"20e1000e88125698264454a884812746c2eb4807","Path":"","Port":11956,"Protocol":"mconn"} service=MConnection
7:35AM ERR mConnection Error EOF module=p2p
7:35AM INF peer disconnected endpoint={} module=p2p peer=20e1000e88125698264454a884812746c2eb4807
7:35AM INF starting service impl=MConnection module=p2p peer={"Hostname":"65.108.227.217","NodeID":"20e1000e88125698264454a884812746c2eb4807","Path":"","Port":11956,"Protocol":"mconn"} service=MConnection
7:35AM INF peer connected endpoint={} module=p2p peer=20e1000e88125698264454a884812746c2eb4807
7:35AM ERR could not use peer for statesync (removing) module=statesync peer=20e1000e88125698264454a884812746c2eb4807
7:35AM ERR could not use peer for dbsync (removing) module=dbsync peer=20e1000e88125698264454a884812746c2eb4807

can you confirm do we need to open port: 11956?
or there is different sets of peers?
In Documentation its given its blank: https://docs.sei.io/full-node/run-a-sei-node/configure-general-settings  ?

**Comment by ratneshpatil-rp** [comment]
Yes i want to setup a pacific-1 node to get transactions and balance!

**Comment by philipsu522** [comment]
Hey @ratneshpatil-rp can you join https://t.me/seinetwork to ask these specific questions?

**Comment by ratneshpatil-rp** [comment]
Mate I dropped query on telegram but no response, can send peers and seeds list

**Comment by philipsu522** [comment]
for achive node @ratneshpatil-rp please use the pacific-1 genesis file and the following seid version:
Seid Version
Tag: 				2.0.48beta
Commit: 			d6a3e606c7d3159e489d3499989f571cceca5fb6 

for other nodes you can follow instructions here: https://docs.sei.io/full-node/run-a-sei-node/join-a-network
