### ISSUE TITLE
[BUG] smart contract tutorial out of date

### ISSUE THREAD

**Issue by sunliang711** [sei-protocol/sei-chain#1038]
Following the documentation fails, the path specified in deploy.sh does not exist. Moreover, the document does not mention how to use the main network and how to use the test network. I'm using the following link: https://docs.sei.io/develop/get-started/counter-smart-contract-tutorial

**Comment by LCyson** [comment]
Thanks for the report, we'll take a look in the following days.

**Comment by duncand0nuts** [comment]
hi @sunliang711 👋 
I made some updates to the counter tutorial, so it should work for you now. 
If you want to find out how to deploy your smart contract to the testnet, you can follow the instructions here: https://docs.sei.io/develop/get-started/testnet-deployment-tutorial
You can also use these instructions to deploy your smart contract to mainnet for development purposes, and you can find a list of public RPCs to use here: https://docs.sei.io/develop/resources
