### ISSUE TITLE
Endpoint for Balance and Transaction.

### ISSUE THREAD

**Issue by ratneshpatil-rp** [sei-protocol/sei-chain#1042]
Hi,

we went through endpoint https://sei-rpc.polkachu.com/

but here we cant find a enpoint or curl query  to grab transactions for particular address and also balance at a blockheight?

**Comment by yzang2019** [comment]
@ratneshpatil-rp  For transactions and balance, I would suggest you check out seiscan block explorer: https://www.seiscan.app/pacific-1

You should be able to search by your wallet address and find all transactions and balance there easily

**Comment by philipsu522** [comment]
Closing this, feel free to reopen if you're still having issues

**Comment by ratneshpatil-rp** [comment]
Hey, 

so for rest of the cosmos- to fetch balance at a block height we have- 
curl --location --request GET 'https://api.data.kava.io/cosmos/bank/v1beta1/balances/kava1wyl4l4zmyas5ymxzyevyfj2j054rn56p637ccn' \
--header 'x-cosmos-block-height: 67622'


which gives us balance.

but same is not working for SEI.
