### ISSUE TITLE
Can't install seid with 'make install'

### ISSUE THREAD

**Issue by coffeemuggg** [sei-protocol/sei-chain#1045]
I am following the tutorial

https://docs.sei.io/develop/get-started/seid

```
git clone https://github.com/sei-protocol/sei-chain
cd sei-chain
git checkout $RELEASE
```

I have go v1.21.1 installed in /usr/bin/go

```make install``` throwing this error

![Screenshot_2023-09-07_at_1 43 01_PM](https://github.com/sei-protocol/sei-chain/assets/92940907/515a46f7-70fc-4a84-abc2-76a097174e03)

**Comment by philipsu522** [comment]
can you use the most recent version of sei which is v3.0.9. also i believe your gopath might be misconfigured, can you please ensure that that's set up correctly?
