### ISSUE TITLE
Change .sei/data directory to a custom path instead of home

### ISSUE THREAD

**Issue by Palak3196** [sei-protocol/sei-chain#1047]
Hi Team,

We have set up .sei mainnet pruned node following the steps here: https://brocha.in/sei/installation/
Even after replacing $HOME/.sei with /DataDisk/.sei, our data is getting dumped to user home directory only (that sits in OS).
How do we change data target path to a custom path (DataDisk in my case).

Thanks,
Palak

**Comment by philipsu522** [comment]
seid has a "--home" flag where you can specify a custom home directory
