### ISSUE TITLE
[BUG] Funds bridged to SEI do not make it to wallet

### ISSUE THREAD

**Issue by njerschow** [sei-protocol/sei-chain#1081]
**Seid version**
price-feeder-2023-09-26-2-gb9fe4ecb

**Chain ID**
pacific-1

**Describe the bug**
I used the bridge on levana UI to bridge from osmo to my compass wallet, which hopped through axelar

**To Reproduce**
1. Go to levana ui
2. Click on bridge
3. bridge axlusdc from osmosis
4. wait for axelar to finish
5. witness funds are not there

**Expected behavior**
Funds to be in wallet

**Screenshots**

**Additional context**
Here is the mintscan tx showing that the funds should have been ibc received:
https://www.mintscan.io/sei/tx/9B33E5B7140308C7A7D6209C949711883D09BDDD8B0C7918BD9EF030C52A2C2C

If you click on my wallet address, you'll see there is no axlUSDC in there. Please advise (amount: $200)

Here is the command to query directly against the sei node: 
`seid q bank balances sei14et32dw7rurl34rxf60mtre55jdl6n27qkh4fh --node https://sei-rpc.polkachu.com`

@qdrln @mturkia @philipsu522 @kwhuo68 @alexanderbez

**Comment by LCyson** [comment]
@njerschow hey ser we're looking into this and will keep you posted soon here

**Comment by njerschow** [comment]
Thanks @LCyson any update? Is it possible the relayer is stuck?

**Comment by LCyson** [comment]
we're seeing this error with Levana UI bridge:
```{
  "error": "cannot unmarshal ICS-20 transfer packet data"
}``

we're talking to Levana team to understand the details, will keep it posted here soon. @njerschow

**Comment by LCyson** [comment]
@njerschow we confirmed this is an ibc packet data incompatibility issue. Squid (Levana bridge provider) uses ibc v3.4.0+ which contains an additional field call `memo`. And this field is currently not supported by Sei ibc (v3.2.0). 

We're looking into how to release your fund, will keep you posted here.

**Comment by LCyson** [comment]
@njerschow right now the fund was refunded to axelar1dv4u5k73pzqrxlzujxg3qp8kvc3pje7jtdvu72npnt5zhq05ejcsn5qme5:
https://axelarscan.io/tx/365686B07B25B60F3B0019D307ED25A944BBB411EA5FBCF3FC58A4A63E98DE06, and we're working with Axelar Squid to get your fund refunded

**Comment by njerschow** [comment]
Thanks for the update. Is there any developments on working with them on this?

**Comment by njerschow** [comment]
Hi is there any update here

**Comment by philipsu522** [comment]
hey @njerschow i'll be taking over - apologies as this was dropped given there were some changes in the teams. If you still need help do you mind letting me know?

**Comment by philipsu522** [comment]
closing for now, feel free to reopen
