### ISSUE TITLE
[SEI-5797] [BUG] Issue Title

### ISSUE THREAD

**Issue by See887777** [sei-protocol/sei-chain#1096]
**Seid version**
Show us output of `seid version --long | head`

**Chain ID**
Which chain are you running into issues with?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

<sub>[SEI-5797](https://linear.app/seilabs/issue/SEI-5797/[bug]-issue-title)</sub>

**Comment by duncand0nuts** [comment]
Hi @See887777 - you have opened a bug report issue but haven't provided any of the requested information. Please leave a comment with the issue you are facing and I will take a look
