### ISSUE TITLE
[SEI-6004] [BUG] - Local Javascript Sei Wallet Connect can't connect to LocalSei running on own machine.

### ISSUE THREAD

**Issue by iguanaus** [sei-protocol/sei-chain#1134]
**Seid version**

```
name: sei
server_name: <appd>
version: 3.0.9
commit: 6baf4dda89d5c5200883d86813cbfa6796fe09ef
build_tags: netgo,ledger
go: go version go1.21.0 darwin/arm64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6
- github.com/CosmWasm/wasmd@v0.27.0 => github.com/sei-protocol/sei-wasmd@v0.0.2
```

**Chain ID**
Local Chain: `sei-chain`

**Describe the bug**
So, Keplr Wallet does allow you to specify your own set endpoints/chain name: see [here](https://forum.cosmos.network/t/cosmos-wallet-for-developers-testnets/4346), but it has to be pushed from the page's javascript.

There are two things blocking this:

1. SeiWalletConnector, does not have this setup to pass the local chain id to Keplr. There is a `devnet` setup in Keplr, but you can't use that for local-dev because the chain-ids must match (or the SeiWalletConnector has to instantiate the new chain). You can see this is a bug (despite the second issue) because with testnet, you must first pre-register the testnet in Keplr.
2. Sei is not setup for CORS to work:

![](https://uploads.linear.app/bf35e7b0-07e0-4b4b-97e4-854fff549edf/08a80f6b-c37a-456e-8f88-11e3956813d8/95881716-9550-4eb0-a581-4de3d7847367?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JmMzVlN2IwLTA3ZTAtNGI0Yi05N2U0LTg1NGZmZjU0OWVkZi8wOGE4MGY2Yi1jMzdhLTQ1NmUtOGY4OC0xMWUzOTU2ODEzZDgvOTU4ODE3MTYtOTU1MC00ZWIwLWE1ODEtNGRlM2Q3ODQ3MzY3IiwiaWF0IjoxNjk5NDY1MTQ0LCJleHAiOjE2OTk1NTE1NDR9.mzgUJFaEAu5Q4kv6alwl-CLpTwFpsjNnNYup8II4tqI)

**To Reproduce**

1. Download the front-end tutorial.
2. Change the wallets, and add in `keplr` to the possible wallet connections.
3. Run the local sei node.
4. Update the front-end application to change the endpoints to the local chain.
5. Try to connect to Keplr from the site \[will fail due to CORS\]
6. You can change the front-end to connect to the testnet, and you will see Keplr fail again (because you have to pre-add the testnet). You shouldn't have to do that, it should recommend to add the testnet.

<sub>From [SyncLinear.com](https://synclinear.com) | [SEI-6004](https://linear.app/seilabs/issue/SEI-6004/[bug]-local-javascript-sei-wallet-connect-cant-connect-to-localsei)</sub>

**Comment by jsidorenko** [comment]
The issue with CORS is still here. All the requests from a locally running frontend application fail due to the cors error coming from http://127.0.0.1:26657/
