### ISSUE TITLE
[Misc] How small can the x/epoch be in your custom module?

### ISSUE THREAD

**Issue by str11ngfello** [sei-protocol/sei-chain#1176]
Just curious about your custom x/epoch module.

Current epoch in the code is set to 60s, can an epoch be 1 second or lower?

**Comment by duncand0nuts** [comment]
hi @str11ngfello 👋 
As far as I understand, the epoch duration is a parameter which can significantly affect network stability. My guess would be that a 1 second epoch would result in validators taking longer to process the epochs than the duration of them, and falling out of sync. 

If you are interested in discussing Sei network parameters, configurations, and future performance improvements, I would suggest posting on our developer forum: https://forum.sei.io/

I am closing this issue for now.
