### ISSUE TITLE
[BUG] Whitepaper link on Coinmarketcap leads to non existent page.

### ISSUE THREAD

**Issue by eirikhanasand** [sei-protocol/sei-chain#1182]
**Seid version**
Not relevant

**Chain ID**
Not relevant

**Describe the bug**
The whitepaper link on the chains listing on Coinmarketcap is invalid. 

**To Reproduce**
1. Go to[ 'Coinmarketcap'](https://coinmarketcap.com/currencies/sei/)
2. Click on whitepaper
3. See error

**Expected behavior**
The link should lead to the most recent whitepaper if there is any, otherwise it should lead to the home of the docs. (https://docs.sei.io)

**Screenshots**
<img width="1511" alt="Visual representation of the issue" src="https://github.com/sei-protocol/sei-chain/assets/59398022/f460ea7d-373f-4891-b314-2e61026852d7">

**Additional context**
Should be fixed to display the seriousness of the project, as both investors and developers will use this link to check how serious the project is, and your plans for future development.

**Comment by duncand0nuts** [comment]
This is fixed now, thank you for spot @eirikhanasand
