### ISSUE TITLE
[Misc] How to query a remote node via `seid`

### ISSUE THREAD

**Issue by DinhNgocAnh** [sei-protocol/sei-chain#1211]
**Seid version**
name: sei
server_name: <appd>
version: SeiDB-4-ge6964868
commit: e6964868cf4964bafb5e9c5f09022577380af581
build_tags: netgo,ledger
go: go version go1.21.5 darwin/amd64
build_deps:
- cosmossdk.io/errors@v1.0.0
- filippo.io/edwards25519@v1.0.0-rc.1
- github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4

**Chain ID**
`atlantic-2`

**Describe the Issue**
How do I interact with a remote node say `atlantic-2` for example instead of local node

**Additional context**

**Comment by farazsth98** [comment]
Pass in the node URL using `--node`.

For example, to query for block information on `atlantic-2`:

```
$ seid q block --node https://rpc.atlantic-2.seinetwork.io:443
```

**Comment by DinhNgocAnh** [comment]
tks @farazsth98
