### ISSUE TITLE
[BUG] Facing local installation error

### ISSUE THREAD

**Issue by SahilDhingraa** [sei-protocol/sei-chain#1213]
![image](https://github.com/sei-protocol/sei-chain/assets/92306979/e007b66d-6a59-461e-a848-aff50169cdd5)

**Comment by Lowdata** [comment]
same issue here

**Comment by purpleguy99** [comment]
same

**Comment by SahilDhingraa** [comment]
My system requirements are not up to the marks that's why I was facing errors, I even tried it on ubuntu but later did I know that I need 64gb of ram
