### ISSUE TITLE
[BUG] Standardization of json format of `lag_status` endpoint data via RPC

### ISSUE THREAD

**Issue by ericjohncarlson** [sei-protocol/sei-chain#1214]
**Seid version**
3.5.1

**Chain ID**
pacific-1

**Describe the bug**
This is a bit nit-picky, but when the node has a higher lag (> 300?), the output of the `lag_status` on the RPC endpoint looks like this:

```
{
  "code": -32604,
  "message": "Lag is too high",
  "data": {
    "current_height": "50529440",
    "max_peer_height": "50529765",
    "lag": "325"
  }
}
```
Once the lag gets below 300 (or so), the data structure changes, and the output looks like this:

```
{
  "current_height": "50530713",
  "max_peer_height": "50530709",
  "lag": "0"
}
```

This change in data structure of the endpoint makes it unnecessarily challenging to parse and build logic from.  

**To Reproduce**
1. curl the RPC endpoint (e.g. `curl -sL http://localhost:26657/lag_status | jq .`)
2. View different data structure per above based on the value of `lag`.

**Expected behavior**
It would be preferred to have a unified data output for consistent parsing.  I would either suggest one of two options

**Option A**:  remove code & message as they're irrelevant to the core data:  the lag #.  Example with large lag.
```
{
  "current_height": "50530713",
  "max_peer_height": "50533709",
  "lag": "3040"
}
```

**Option B**:  Keep consistent data structure, with or without code and message.  Example of 0 lag.
```
{
  "code": 0,
  "message": "",
  "data": {
    "current_height": "50530713",
    "max_peer_height": "50530709",
    "lag": "0"
  }
}
```

**Comment by yzang2019** [comment]
Thanks for bringing this up, we'll look into this soon

**Comment by yzang2019** [comment]
@ericjohncarlson The reason why code and message is showing up here is because underneath in RPC server, when lag > 300 or whatever threshold, the http server is returning an Error Response with a special http error code, so it has a different body format when it's not erroring out.

**Comment by yzang2019** [comment]
Let me look into what's the best way to fix it

**Comment by yzang2019** [comment]
PR is out: https://github.com/sei-protocol/sei-tendermint/pull/187

**Comment by duncand0nuts** [comment]
@ericjohncarlson ty for the spot - I am closing this issue for now. You can comment here if you you want to reopen it. 🙌
