### ISSUE TITLE
[QUESTION] instruction token create 

### ISSUE THREAD

**Issue by damartripamungkas** [sei-protocol/sei-chain#1223]
If you want to create a token, do you have to install all of these packages? I mean if in ERC20 ethereum creating a token is enough to use solidity code, compile, then send it to the RPC URL, while if SEI how? because the documentation is too difficult to understand.

**Comment by duncand0nuts** [comment]
Yes, you need to build your token contract locally before you deploy it, which requires you to install the toolchain.
