### ISSUE TITLE
[BUG] Missing transaction in my full node.

### ISSUE THREAD

**Issue by jasoncsli** [sei-protocol/sei-chain#1231]
**Seid version**
````
name: sei
server_name: <appd>
version: 3.5.0
commit: ff7ca2c516aa53652459cd1fa9f71cf014c6d81e
build_tags: netgo ledger,
go: go version go1.18.1 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6
- github.com/CosmWasm/wasmd@v0.27.0 => github.com/sei-protocol/sei-wasmd@v0.0.4
````

**Chain ID**
atlantic-2

**Describe the bug**
My node is syncing with the atlantic-2 network, and my node often lags behind. Therefore, I am using auto restart after behind 300 blocks. And I am using state sync for my node.

I find out some blocks have transactions in `cosmos/base/tendermint/v1beta1/blocks/xxxxx` api, but `cosmos/tx/v1beta1/txs?events=tx.height=xxxxx` returns no transaction. 

Do you know why this issue happens? And what should I do to help my node have all transactions for blocks.

**Comment by yzang2019** [comment]
Yeah, this is a bug in cosmos sdk where during restart there might be some transactions not getting correctly indexed, leading to missing transactions. There isn't any long term fix yet, but there's a workaround by following this guide: https://github.com/sei-protocol/sei-chain/tree/main/tools

The step is to:
1. Use the tx-scanner tool to scan missing transactions
2. Stop seid process
3. Run tendermint command to reindex the missing tx events
