### ISSUE TITLE
Make install Error

### ISSUE THREAD

**Issue by messiisgreat** [sei-protocol/sei-chain#1261]
Version: v3.6.1

'sed' is not recognized as an internal or external command,
operable program or batch file.
Access denied - E:/SEI/SEI-CHAIN
File not found - -NAME

I installed every dependencies but faced these error when installing seid(In windows)

_____________________________________________

go install -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=sei -X github.com/cosmos/cosmos-sdk/version.ServerName=seid -X github.com/cosmos/cosmos-sdk/version.Version= -X github.com/cosmos/cosmos-sdk/version.Commit=593ed187dc60b81d7fa42c15b794f124b4b1cd46 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo ledger,"' ./cmd/seid
# github.com/sei-protocol/sei-chain/cmd/seid
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_analyze_code':
/tmp/go-build/cgo-gcc-prolog:56: undefined reference to `analyze_code'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_execute':
/tmp/go-build/cgo-gcc-prolog:90: undefined reference to `execute'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_get_metrics':
/tmp/go-build/cgo-gcc-prolog:113: undefined reference to `get_metrics'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_ibc_channel_close':
/tmp/go-build/cgo-gcc-prolog:146: undefined reference to `ibc_channel_close'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_ibc_channel_connect':
/tmp/go-build/cgo-gcc-prolog:179: undefined reference to `ibc_channel_connect'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_ibc_channel_open':
/tmp/go-build/cgo-gcc-prolog:212: undefined reference to `ibc_channel_open'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_ibc_packet_ack':
/tmp/go-build/cgo-gcc-prolog:245: undefined reference to `ibc_packet_ack'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_ibc_packet_receive':
/tmp/go-build/cgo-gcc-prolog:278: undefined reference to `ibc_packet_receive'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_ibc_packet_timeout':
/tmp/go-build/cgo-gcc-prolog:311: undefined reference to `ibc_packet_timeout'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_init_cache':
/tmp/go-build/cgo-gcc-prolog:337: undefined reference to `init_cache'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_instantiate':
/tmp/go-build/cgo-gcc-prolog:371: undefined reference to `instantiate'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_load_wasm':
/tmp/go-build/cgo-gcc-prolog:395: undefined reference to `load_wasm'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_migrate':
/tmp/go-build/cgo-gcc-prolog:428: undefined reference to `migrate'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_pin':
/tmp/go-build/cgo-gcc-prolog:449: undefined reference to `pin'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_query':
/tmp/go-build/cgo-gcc-prolog:479: undefined reference to `query'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_reply':
/tmp/go-build/cgo-gcc-prolog:512: undefined reference to `reply'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_save_wasm':
/tmp/go-build/cgo-gcc-prolog:536: undefined reference to `save_wasm'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_sudo':
/tmp/go-build/cgo-gcc-prolog:569: undefined reference to `sudo'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_C2func_unpin':
/tmp/go-build/cgo-gcc-prolog:590: undefined reference to `unpin'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_analyze_code':
/tmp/go-build/cgo-gcc-prolog:609: undefined reference to `analyze_code'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_execute':
/tmp/go-build/cgo-gcc-prolog:639: undefined reference to `execute'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_get_metrics':
/tmp/go-build/cgo-gcc-prolog:658: undefined reference to `get_metrics'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_ibc_channel_close':
/tmp/go-build/cgo-gcc-prolog:687: undefined reference to `ibc_channel_close'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_ibc_channel_connect':
/tmp/go-build/cgo-gcc-prolog:716: undefined reference to `ibc_channel_connect'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_ibc_channel_open':
/tmp/go-build/cgo-gcc-prolog:745: undefined reference to `ibc_channel_open'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_ibc_packet_ack':
/tmp/go-build/cgo-gcc-prolog:774: undefined reference to `ibc_packet_ack'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_ibc_packet_receive':
/tmp/go-build/cgo-gcc-prolog:803: undefined reference to `ibc_packet_receive'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_ibc_packet_timeout':
/tmp/go-build/cgo-gcc-prolog:832: undefined reference to `ibc_packet_timeout'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_init_cache':
/tmp/go-build/cgo-gcc-prolog:854: undefined reference to `init_cache'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_instantiate':
/tmp/go-build/cgo-gcc-prolog:884: undefined reference to `instantiate'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_load_wasm':
/tmp/go-build/cgo-gcc-prolog:904: undefined reference to `load_wasm'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_migrate':
/tmp/go-build/cgo-gcc-prolog:933: undefined reference to `migrate'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_pin':
/tmp/go-build/cgo-gcc-prolog:950: undefined reference to `pin'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_query':
/tmp/go-build/cgo-gcc-prolog:976: undefined reference to `query'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_reply':
/tmp/go-build/cgo-gcc-prolog:1017: undefined reference to `reply'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_save_wasm':
/tmp/go-build/cgo-gcc-prolog:1037: undefined reference to `save_wasm'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_sudo':
/tmp/go-build/cgo-gcc-prolog:1066: undefined reference to `sudo'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_unpin':
/tmp/go-build/cgo-gcc-prolog:1083: undefined reference to `unpin'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000003.o: in function `_cgo_cdcbe8c3bf31_Cfunc_release_cache':
/tmp/go-build/cgo-gcc-prolog:991: undefined reference to `release_cache'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000004.o: in function `_cgo_cdcbe8c3bf31_Cfunc_destroy_unmanaged_vector':
/tmp/go-build/cgo-gcc-prolog:49: undefined reference to `destroy_unmanaged_vector'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000004.o: in function `_cgo_cdcbe8c3bf31_Cfunc_new_unmanaged_vector':
/tmp/go-build/cgo-gcc-prolog:67: undefined reference to `new_unmanaged_vector'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000005.o: in function `_cgo_cdcbe8c3bf31_C2func_version_str':
/tmp/go-build/cgo-gcc-prolog:53: undefined reference to `version_str'
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RENAIS~1\AppData\Local\Temp\go-link-3500040826\000005.o: in function `_cgo_cdcbe8c3bf31_Cfunc_version_str':
/tmp/go-build/cgo-gcc-prolog:72: undefined reference to `version_str'
collect2.exe: error: ld returned 1 exit status

make: *** [Makefile:69: install] Error 1

1. install all of dependencies on windows 10 using Chocolatey

2. git clone https://github.com/sei-protocol/sei-chain
3. cd sei-chain
4. git checkout v3.6.1
5. make install

**Expected behavior**
occured error above I described

Is Most important below?

make: *** [Makefile:69: install] Error 1

![image](https://github.com/sei-protocol/sei-chain/assets/134148939/6ec59358-764c-4738-906d-85bdf7966a2d)

**Comment by messiisgreat** [comment]
Anybody can help me?

**Comment by itsmelodewyk** [comment]
`'sed' is not recognized as an internal or external command` - you are missing `sed` which is an application generally available in Linux. I see that you are using Windows; the prerequisite is to use Linux. There are ways around this by, eg. installing `cygwin` but who knows what other errors you might run into.

**Comment by messiisgreat** [comment]
Thank you @itsmelodewyk 

But in sei docs, they support us on windows using Chocolatey.

And I tryed again on linux(ubuntu 22.04) has similar error.

![image](https://github.com/sei-protocol/sei-chain/assets/134148939/4f600faa-ec6c-4c83-afff-8b104bb21108)

Or when I tryed make install as root user, error was below

![image](https://github.com/sei-protocol/sei-chain/assets/134148939/103f3bfb-9543-4334-956d-71063975e608)

Could you share me more how I can fix it?

**Comment by itsmelodewyk** [comment]
Just as a note, I'm not a SEI developer and just commenting based on the errors you are getting. For the first screenshot you need to update go version >= 1.19. 

For the second issue, I'll suggest you fix the first issue and not run as root.

**Comment by messiisgreat** [comment]
Thank you.
But that is comon solution and in this case, how can I upgrade go version without any risk?

**Comment by itsmelodewyk** [comment]
Depends on your package manager. Ubuntu? `sudo apt-get install golang`

**Comment by messiisgreat** [comment]
I did it.
but it is not working.

**Comment by preayham** [comment]
I am getting `collect2.exe: error: ld returned 1 exit status` as well on windows. I installed all the pre-requisites, and have go1.21.6.

**Comment by theghostmac** [comment]
Mine also doesn't work. I use a macOS.

<img width="1276" alt="image" src="https://github.com/sei-protocol/sei-chain/assets/83423188/ac4d2998-ec93-4747-b244-0d2457a8b668">

I have replicated it on another computer, terminals. etc., and I got the same issue.

**Comment by panos321** [comment]
You have to install cmake. then run make install.

**Comment by messiisgreat** [comment]
> You have to install cmake. then run make install.

Thank you for your kind reply.
But it is still not working yet

**Comment by philipsu522** [comment]
closing since this should be fixed, but feel free to reopen if you're still having issues
