### ISSUE TITLE
[BUG] Get Started documentation, Errors and confusion, would love to help contribute

### ISSUE THREAD

**Issue by mecoookie** [sei-protocol/sei-chain#1294]
**Seid version**
name: sei
server_name: <appd>
version: 3.6.2
commit: ea5d477b82d80b278c6577a467ee1c8d4c7465d9
build_tags: netgo,ledger
go: go version go1.21.6 darwin/arm64
build_deps:
- cosmossdk.io/errors@v1.0.0
- filippo.io/edwards25519@v1.0.0-rc.1
- github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4

**Chain ID**
All

**Describe the bug**
I'm working through the documentation for "Get Started." (https://docs.sei.io/develop/get-started) The sub-header is "Use this beginner-friendly guide to start building on Sei," but as a beginning user of Sei coming from another chain, I'm hitting errors in the commands, terminology that doesn't make sense, or typos. Things that as a beginner it's highly improbable to overcome.

I would love to contribute to make it better! 

I'd love to connect to the team who wrote "get started," and as I try to work through it, update or contribute additional steps needed to make things work.  

For example, right now I'm running the command as described in the parallelization tutorial, where you're supposed to type
seid q accesscontrol wasm-dependency-mapping (contract addresss)

And I'm receiving an error
"Error: rpc error: code = InvalidArgument desc = "

I'm sure as an advanced user, the solution to this would be obvious, but as someone new to SEI, it's not something I'm able to overcome without difficulty in the "get started" section. (I'm assuming that a step that's been skipped in here is somehow setting up RPC settings for said while running a local node, but It's probably going to take me quite a bit to figure out).

There's other things as well, including I'd love to help add additions to the steps in parallelization with the typo in the name parallelization.sh vs parallelism.sh (same script called with different names), or clarifying that the admin wallet from the previous step is what's being requested in "your_contract_address"

I hope I can help give feedback to improve the process so more people can come onboard.... Myself included! 

It's been 3 days now and I'm doing my best to keep pushing through, even though many steps don't work at first.

once again, hope I can help!

**To Reproduce**
1. Go to (https://docs.sei.io/develop/get-started/counter-smart-contract-tutorial)
2. Create a sandbox VM so no system variables are set
2. Try work through the tutorials with strict adherence to the commands and scripts presented. At some point it will stop working. 

**Expected behavior**
Not to feel entitled... I would expect getting started walkthroughs would work without errors. 

**Additional context**
Seid seems great! I'm trying to contribute with constructive feedback on onboarding as a new user with 2-3 years blockchain programming experience, trying to work on SEI. 

I hope I can help and contribute to the docs.

**Comment by philipsu522** [comment]
@mecoookie we've revamped our docs, feel free to take a look and create a new ticket if you'd like!
@cordt-sei built a pretty helpful tool here to run a node: https://www.docs.sei.io/dev-node/quickstart

**Comment by cordt-sei** [comment]
Oh sorry there was actually a syntax error causing the docs page to fall back to a previous version instead of just 404ing the entire thing. It should be fixed now, can you check again? @mecoookie
