### ISSUE TITLE
Missing status query interface

### ISSUE THREAD

**Issue by tpkeeper** [sei-protocol/sei-chain#1369]
https://github.com/sei-protocol/sei-chain/blob/a6acddaf661bfe8bb4841c017d4c92a289623fea/precompiles/staking/Staking.sol#L10

**Comment by tpkeeper** [comment]
Hello, when will this feat be implemented? Developing staking-based applications will use the staking query interface

**Comment by philipsu522** [comment]
it's been implemented!
