### ISSUE TITLE
After starting 4 local Docker nodes, the price-feeder-x continues to receive errors.

### ISSUE THREAD

**Issue by sdjasj** [sei-protocol/sei-chain#1384]
**Seid version**
name: sei
server_name: <appd>
version: v4.1.4-evm-devnet
commit: 6e26498471079268799dd14091ca7256680cb82f
build_tags: netgo ledger,
go: go version go1.22.0 linux/amd64
build_deps:
- cosmossdk.io/errors@v1.0.0
- filippo.io/edwards25519@v1.0.0-rc.1
- github.com/99designs/keyring@v1.2.1

**Chain ID**
None

**Describe the bug**
After starting 4 local Docker nodes, the price-feeder-x continues to receive errors.

**To Reproduce**
1.git checkout v4.1.4-evm-devnet
2.run `make docker-cluster-start`
3.after some time, see the `build/generated/logs/price-feeder-0.log`

**Expected behavior**
There won't be any error messages, or the error messages won't be continuously received.

**Screenshots**
![228e42cbee7a8c9be261eebd402968d](https://github.com/sei-protocol/sei-chain/assets/89853352/09c9ba6e-98fb-40e0-bc9c-88e11ceda1e5)

**Additional context**

**Comment by philipsu522** [comment]
ah i don't believe we run oracle price feeders in our docker container which means the validators get jailed after a while. Typically the docker cluster is meant for quick verification instead of long-running chains

you can try running `seid q staking validators` to verify they are jailed
