### ISSUE TITLE
[BUG] conflicting transactions executed in parallel result in "incorrect account sequence"

### ISSUE THREAD

**Issue by sdjasj** [sei-protocol/sei-chain#1431]
**Seid version**
```
name: sei
server_name: <appd>
version: v4.1.4-evm-devnet
commit: 6e26498471079268799dd14091ca7256680cb82f
build_tags: netgo ledger,
go: go version go1.22.0 linux/amd64
build_deps:
- cosmossdk.io/errors@v1.0.0
- filippo.io/edwards25519@v1.0.0-rc.1
- github.com/99designs/keyring@v1.2.1
```

**Chain ID**
Local 4-docker-node chain with EVM parallel mechanism

**Describe the bug**
Conflicting transactions executed in parallel result in "incorrect account sequence", leading to transaction failures.

**To Reproduce**
1.run a 4-docker-node private chain locally.
2.Deploy some Solidity contracts through Forge, where the functions of the contracts conflict in accessing state variables.
4.Use cast to send transactions in parallel, some transactuions return the message of "incorrect account sequence" and fail to execute.
5.Resend the transaction and it can be successfully executed.

**Expected behavior**
conflicting transactions executed in parallel should not result in "incorrect account sequence", and all transactions can be executed successfully. 

**Screenshots**
The conflicting transactions executed in parallel and one return the message of "incorrect account sequence"
![928616caaea3ae8b13b6234511be154](https://github.com/sei-protocol/sei-chain/assets/89853352/36c33ae6-7cdf-4118-a3bd-993c20f77584)

Resend the transaction  and it can be successfully executed
![fb63b864ed5543b40b2daa75e1e7054](https://github.com/sei-protocol/sei-chain/assets/89853352/e862e654-cb3d-47af-993d-a26dcc7bef9e)

**Additional context**

**Comment by philipsu522** [comment]
we've made many fixes to account seqno tracking in evm, can you reopen if this is still an issue?
