### ISSUE TITLE
can't find the keys both by using --keyring-backed file and the default one, even if they have been added and are present .

### ISSUE THREAD

**Issue by Peppeinsa** [sei-protocol/sei-chain#1439]
**Seid version**
v4.1.4-evm-devnet

**Describe the Issue**
when i use this command:
seid tx tokenfactory create-denom Coin --from=Wallet2 --chain-id=arctic-1 --node=https://rpc.arctic-1.seinetwork.io/ --broadcast-mode=block --fees=20000usei --keyring-backend file

this is what i get:
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account sei1gzs74t2nceppd5s0g76nvruwh4swa24g6r29cg not found: key not found

How can i solve this problem?

**Comment by philipsu522** [comment]
make sure you're using --keyring-backend file when querying
