### ISSUE TITLE
[BUG]  Conflict in transaction execution leads to inconsistent updates of state variables

### ISSUE THREAD

**Issue by sdjasj** [sei-protocol/sei-chain#1446]
**Seid version**
```
name: sei
server_name: <appd>
version: v4.1.4-evm-devnet
commit: 6e26498471079268799dd14091ca7256680cb82f
build_tags: netgo ledger,
go: go version go1.22.0 linux/amd64
build_deps:
- cosmossdk.io/errors@v1.0.0
- filippo.io/edwards25519@v1.0.0-rc.1
- github.com/99designs/keyring@v1.2.1
```

**Chain ID**
Local 4-docker-node chain with EVM parallel mechanism

**Describe the bug**
I continuously send conflicting transactions to the local 4-node chain with EVM parallel mechanism. For instance, different functions of a contract access different state variables of the contract, or functions of different contracts access each other's state variables. I simulate the execution of transactions of the local chain locally. After testing for a few hours, I notice discrepancies between the local results and the results on the chain.

**To Reproduce**
1. Deploy contract.
2. Send transactions with conflicts, such as different functions of a contract accessing different state variables of the same contract, or functions of different contracts accessing each other's state variables.
3. Simulate transaction execution of the local chain locally (a transaction is considered successful only when the transaction receipt contains `status:0x1`.).
4. Inconsistency between local and on-chain results.

**Expected behavior**
 Local and on-chain results should be consistent.

**Screenshots**
![0131c7a87689908eddfebfb8cee4895](https://github.com/sei-protocol/sei-chain/assets/89853352/68b716ab-cd29-4f8c-9d1f-613d87fe041f)

**Comment by philipsu522** [comment]
we've made several fixes to EVM, please let us know if this is still an issue in a new ticket!
