### ISSUE TITLE
[Misc] Cosmovisor upgrades usage

### ISSUE THREAD

**Issue by carloscip** [sei-protocol/sei-chain#1450]
**Seid version**
```
name: sei
server_name: <appd>
version: v3.7.0
commit: de428b1bcfaa6e5c6a47db2b76eedba5abb56a25
build_tags: netgo ledger,
go: go version go1.22.1 linux/arm64
build_deps:
- cosmossdk.io/errors@v1.0.0
- filippo.io/edwards25519@v1.0.0-rc.1
- github.com/99designs/keyring@v1.2.1
```
**Chain ID**
atlantic-2, but applies to pacific-1

**Describe the Issue**
How to manage cosmovisor binary upgrades? There's no file `upgrade-info.json` in the github, and using flag ```DAEMON_ALLOW_DOWNLOAD_BINARIES=true``` is not recommended.

**Additional context**
Just as clarification I am using cosmovisor not as a systemd service but rather in a docker environment. Will the `DAEMON_RESTART_AFTER_UPGRADE=true` restart work in this scenario?

Also, it'd be really appreciated if more information regarding cosmovisor usage with sei is present in the official docs.

**Comment by luislucena16** [comment]
can anyone help us with this? thanks in advance! cc @BrandonWeng @philipsu522 @udpatil

**Comment by philipsu522** [comment]
hey @luislucena16 let me know if you still need help here. The open source cosmovisor docs should be sufficient since we haven't modified things: https://github.com/cosmos/cosmos-sdk/blob/main/tools/cosmovisor/README.md
