### ISSUE TITLE
[BUG] The execution of conflicting transactions results in memory leaks.

### ISSUE THREAD

**Issue by sdjasj** [sei-protocol/sei-chain#1554]
**Seid version**
name: sei
server_name: <appd>
version: v4.1.7-evm-devnet
commit: 6e0c934a54a15a6f69ffb97a039ed7698a66ded3
build_tags: netgo ledger,
go: go version go1.22.0 linux/amd64
build_deps:
- cosmossdk.io/errors@v1.0.0
- filippo.io/edwards25519@v1.0.0-rc.1
- github.com/99designs/keyring@v1.2.1

**Chain ID**
Local 4-docker-node chain with EVM parallel mechanism

**Describe the bug**
I continuously send conflicting transactions to the local 4-node chain with EVM parallel mechanism. For instance, different functions of a contract access different state variables of the contract, or functions of different contracts access each other's state variables. After executing conflicting transactions on the  chains for a few hours, the 128GB memory is almost fully occupied.

**To Reproduce**
1. Deploy contract.
2. Send transactions with conflicts, such as different functions of a contract accessing different state variables of the same contract, or functions of different contracts accessing each other's state variables.
3. The memory usage keeps increasing, eventually almost filling up the 128GB of memory.

**Expected behavior**
The memory usage should be maintained at a stable level, preferably at a lower level.

**Screenshots**
![9bb2a6aed37ca1398bfbb5a5ec22c1b](https://github.com/sei-protocol/sei-chain/assets/89853352/2962d29d-b0d9-491e-95f5-dbeecc7ff59e)

**Comment by philipsu522** [comment]
@sdjasj can you let us know if this is still an issue? we've fixed memory leak issues around receipts

**Comment by philipsu522** [comment]
closing for now, feel free to reopen
