### ISSUE TITLE
Wrapped SEI (WSEI) for EVM

### ISSUE THREAD

**Issue by nidz-the-fact** [sei-protocol/sei-chain#1705]
### Search before asking

- [X] I searched in the [issues](https://github.com/sei-protocol/sei-chain/issues) and found nothing similar.

### Motivation

I think there should be a **Wrapped SEI (WSEI)** token from the **official** `Sei Network`.
https://seitrace.com/tokens?chain=pacific-1

![image](https://github.com/sei-protocol/sei-chain/assets/106298826/c38f9743-7e0d-4fef-9ab1-6f942ff15479)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by philipsu522** [comment]
this has been deployed! https://seitrace.com/token/0xE30feDd158A2e3b13e9badaeABaFc5516e95e8C7?chain=pacific-1
