### ISSUE TITLE
[BUG] panic: recovered: runtime error: integer divide by zero #514

### ISSUE THREAD

**Issue by jack091090** [sei-protocol/sei-chain#1716]
**Seid version**
name: sei
server_name: <appd>
version: v5.5.2
commit: c92dc5fb3b15e8a62a3fcf8b7c53cfb3ce940119
build_tags: netgo,ledger
go: go version go1.21.9 darwin/amd64
build_deps:
- cosmossdk.io/errors@v1.0.0
- filippo.io/edwards25519@v1.0.0-rc.1
- github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4

**Chain ID**
- chain-id: pacific-1
- genesis: https://raw.githubusercontent.com/sei-protocol/testnet/main/pacific-1/genesis.json

**Describe the bug**
I follow this document to setup a full node but I receive this error . How to fix it
https://www.docs.sei.io/dev-node/node-operators

**Additional context**
macbookpro@Jack sei-chain % seid start
5:02PM INF --tracing not passed in, tracing is not enabled
5:02PM INF Creating node metrics provider
5:02PM INF Starting Process
5:02PM INF SeiDB SC is enabled, running node with StoreV2 commit store
5:02PM INF Start catching up and replaying the MemIAVL changelog file
5:02PM INF Finished the replay and caught up to version 0
5:02PM INF starting node with ABCI Tendermint in-process
5:02PM INF Adding new peer de8b1df70c7a8817ed121908e7c6e6059f4238f9 with address mconn://de8b1df70c7a8817ed121908e7c6e6059f4238f9@3.142.50.176:26656 to peer store
module=p2p
5:02PM INF Adding new peer 7a962f3a928ca4e0e58355e6e798aba1ea253272 with address mconn://7a962f3a928ca4e0e58355e6e798aba1ea253272@34.242.85.117:26656 to peer store
module=p2p
5:02PM INF starting service impl=Node service=Node
5:02PM INF starting service impl=proxyClient module=proxy service=proxyClient
5:02PM INF starting service impl=localClient service=localClient
5:02PM INF starting service impl=EventBus module=eventbus service=EventBus
5:02PM INF starting service impl=PubSub module=events service=PubSub
5:02PM INF starting service impl=IndexerService module=txindex service=IndexerService
5:02PM INF ABCI Handshake App Info hash= height=0 module=handshaker protocol-version=0 software-version=v5.5.2
5:02PM INF ABCI Replay Blocks appHeight=0 module=handshaker stateHeight=0 storeHeight=0
5:02PM INF asserting crisis invariants inv=1/11 module=x/crisis name=bank/nonnegative-outstanding
5:02PM INF asserting crisis invariants inv=2/11 module=x/crisis name=bank/total-supply
5:02PM INF asserting crisis invariants inv=3/11 module=x/crisis name=gov/module-account
5:02PM INF asserting crisis invariants inv=4/11 module=x/crisis name=distribution/nonnegative-outstanding
5:02PM INF asserting crisis invariants inv=5/11 module=x/crisis name=distribution/can-withdraw
5:02PM INF asserting crisis invariants inv=6/11 module=x/crisis name=distribution/reference-count
5:02PM INF asserting crisis invariants inv=7/11 module=x/crisis name=distribution/module-account
5:02PM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/module-accounts
5:02PM INF asserting crisis invariants inv=9/11 module=x/crisis name=staking/nonnegative-power
5:02PM INF asserting crisis invariants inv=10/11 module=x/crisis name=staking/positive-delegation
5:02PM INF asserting crisis invariants inv=11/11 module=x/crisis name=staking/delegator-shares
5:02PM INF asserted all invariants duration=0.736684 height=0 module=x/crisis
5:02PM INF Current epoch 0
panic: recovered: runtime error: integer divide by zero
stack:
goroutine 1 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func1({0x102188f20?, 0x104775710})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/baseapp/recovery.go:91 +0x26
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func2({0x102188f20?, 0x104775710?})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/baseapp/recovery.go:40 +0x2d
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x102188f20, 0x104775710}, 0xc0009c07e0?)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/baseapp/recovery.go:29 +0x2f
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x102188f20, 0x104775710}, 0x1?)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/baseapp/recovery.go:34 +0x53
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x102188f20, 0x104775710}, 0x0?)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/baseapp/recovery.go:34 +0x53
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/baseapp/baseapp.go:880 +0x325
panic({0x102188f20?, 0x104775710?})
/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle.func1()
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/x/auth/ante/setup.go:69 +0x1d8
panic({0x102188f20?, 0x104775710?})
/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/cosmos/cosmos-sdk/store/types.(*infiniteMultiplierGasMeter).adjustGas(...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/store/types/gas.go:289
github.com/cosmos/cosmos-sdk/store/types.(*infiniteMultiplierGasMeter).ConsumeGas(0x18?, 0x1?, {0x10253310c?, 0x15?})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/store/types/gas.go:293 +0x50
github.com/cosmos/cosmos-sdk/store/gaskv.(*Store).Get(0xc000940f00, {0xc000801530, 0x15, 0x18})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/store/gaskv/store.go:42 +0x4a
github.com/cosmos/cosmos-sdk/x/auth/keeper.AccountKeeper.GetAccount({{0x103199e38, 0xc0008afb50}, {0x1031c9f70, 0xc000721860}, {{0x1031c9f70, 0xc000721860}, 0xc0005d6460, {0x103199e38, 0xc0008afbd0}, {0x103199e60, ...}, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/x/auth/keeper/account.go:37 +0x126
github.com/cosmos/cosmos-sdk/x/auth/ante.DeductFeeDecorator.checkDeductFee({{0x1031b5588, 0xc0007b7ea0}, {0x14ddb97f0, 0xc0007b2340}, {0x1031925c0, 0xc00070a0c0}, {{0x1031c9f70, 0xc000721860}, 0xc0005d6460, {0x103199e38, ...}, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/x/auth/ante/fee.go:177 +0x3bf
github.com/cosmos/cosmos-sdk/x/auth/ante.DeductFeeDecorator.AnteHandle({{0x1031b5588, 0xc0007b7ea0}, {0x14ddb97f0, 0xc0007b2340}, {0x1031925c0, 0xc00070a0c0}, {{0x1031c9f70, 0xc000721860}, 0xc0005d6460, {0x103199e38, ...}, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/x/auth/ante/fee.go:139 +0x15b
github.com/sei-protocol/sei-chain/app/antedecorators.GaslessDecorator.handleWrapped({{0xc000993770, 0x1, 0x1}, {{0x1031c9f70, 0xc000721860}, {0x103199e38, 0xc0008afc40}, {0x103199e88, 0xc0008afd00}, {{0x1031c9f70, ...}, ...}, ...}}, ...)
/Users/macbookpro/go/src/github.com/sei-protocol/sei-chain/app/antedecorators/gasless.go:61 +0x147
github.com/sei-protocol/sei-chain/app/antedecorators.GaslessDecorator.AnteHandle({{0xc000993770, 0x1, 0x1}, {{0x1031c9f70, 0xc000721860}, {0x103199e38, 0xc0008afc40}, {0x103199e88, 0xc0008afd00}, {{0x1031c9f70, ...}, ...}, ...}}, ...)
/Users/macbookpro/go/src/github.com/sei-protocol/sei-chain/app/antedecorators/gasless.go:48 +0x390
github.com/cosmos/cosmos-sdk/types.chainAnteDecoratorHandlers.func1({{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0006f3fc0}, {{0x0, 0x0}, {0xc000988310, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/types/handler.go:81 +0x136
github.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle({}, {{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0006f3fc0}, {{0x0, 0x0}, {0xc000988310, 0x9}, 0x0, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/x/auth/ante/setup.go:74 +0x210
github.com/cosmos/cosmos-sdk/types.WrappedAnteDecorator.AnteHandle(...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/types/handler.go:122
github.com/cosmos/cosmos-sdk/types.chainAnteDecoratorHandlers.func1({{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0006f3fc0}, {{0x0, 0x0}, {0xc000988310, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/types/handler.go:81 +0x136
github.com/sei-protocol/sei-chain/x/evm/ante.EVMRouterDecorator.AnteHandle({, , , }, {{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0006f3fc0}, {{0x0, 0x0}, ...}, ...}, ...)
/Users/macbookpro/go/src/github.com/sei-protocol/sei-chain/x/evm/ante/router.go:40 +0x1d7
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(, {{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0002c37c0}, {{0x0, 0x0}, {0xc000988310, 0x9}, 0x0, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/baseapp/baseapp.go:918 +0xbd3
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx(, {{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0002c37c0}, {{0x0, 0x0}, {0xc000988310, 0x9}, 0x0, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/baseapp/abci.go:299 +0x34d
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs({{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0002c37c0}, {{0x0, 0x0}, {0xc000988310, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/x/genutil/gentx.go:113 +0x20a
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/x/genutil/genesis.go:18
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{}, {, }, {, }, , {, }}, {{0x1031b5928, 0xc0007af3e0}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/x/genutil/module.go:99 +0x13e
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(, {{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0002c37c0}, {{0x0, 0x0}, {0xc000988310, 0x9}, 0x0, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/types/module/module.go:341 +0x21d
github.com/sei-protocol/sei-chain/app.(*App).InitChainer(, {{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0002c37c0}, {{0x0, 0x0}, {0xc000988310, 0x9}, 0x0, ...}, ...}, ...)
/Users/macbookpro/go/src/github.com/sei-protocol/sei-chain/app/app.go:1053 +0x2ae
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000033400, {0x100000001?, 0xc00076c980?}, 0x100071636?)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/baseapp/abci.go:73 +0x559
github.com/tendermint/tendermint/internal/proxy.(*proxyClient).InitChain(0xc00019cf50, {0x1031b5960, 0xc0000bc910}, 0xc0004e5740?)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.3/internal/proxy/client.go:129 +0x16e
github.com/tendermint/tendermint/internal/consensus.(*Handshaker).ReplayBlocks(, {, }, {{{0xb, 0x0}, {0xc00014f350, 0x11}}, {0xc000988e50, 0x9}, 0x1, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.3/internal/consensus/replay.go:312 +0xf45
github.com/tendermint/tendermint/internal/consensus.(*Handshaker).Handshake(0xc000b2fd18, {0x1031b5960, 0xc0000bc910}, {0x1031d7b40?, 0xc00019cf50?})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.3/internal/consensus/replay.go:268 +0x3db
github.com/tendermint/tendermint/node.(*nodeImpl).OnStart(0xc0006eb500, {0x1031b5960, 0xc0000bc910})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.3/node/node.go:510 +0x2d5
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc0006eb500, {0x1031b5960?, 0xc0000bc910})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.3/libs/service/service.go:117 +0x203
github.com/cosmos/cosmos-sdk/server.startInProcess(, {{0x0, 0x0, 0x0}, {0x1031de4f0, 0xc000947770}, {0xc0009d4b90, 0x9}, {0x1031bd528, 0xc00033e680}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/server/start.go:402 +0x967
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000303b00?, {0x104803f20?, 0x0?, 0x0?})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/server/start.go:207 +0x8d9
github.com/spf13/cobra.(*Command).execute(0xc0001d8900, {0x104803f20, 0x0, 0x0})
/Users/macbookpro/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000445500)
/Users/macbookpro/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
/Users/macbookpro/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
/Users/macbookpro/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x1046e6538?, {0xc000412738, 0x16})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/server/cmd/execute.go:35 +0x145
main.main()
/Users/macbookpro/go/src/github.com/sei-protocol/sei-chain/cmd/seid/main.go:16 +0x2b
: panic

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs({{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0002c37c0}, {{0x0, 0x0}, {0xc000988310, 0x9}, 0x0, {0x0, ...}, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/x/genutil/gentx.go:115 +0x2f7
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/x/genutil/genesis.go:18
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{}, {, }, {, }, , {, }}, {{0x1031b5928, 0xc0007af3e0}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/x/genutil/module.go:99 +0x13e
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(, {{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0002c37c0}, {{0x0, 0x0}, {0xc000988310, 0x9}, 0x0, ...}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/types/module/module.go:341 +0x21d
github.com/sei-protocol/sei-chain/app.(*App).InitChainer(, {{0x1031b5928, 0xc0007af3e0}, {0x1031d31a0, 0xc0002c37c0}, {{0x0, 0x0}, {0xc000988310, 0x9}, 0x0, ...}, ...}, ...)
/Users/macbookpro/go/src/github.com/sei-protocol/sei-chain/app/app.go:1053 +0x2ae
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000033400, {0x100000001?, 0xc00076c980?}, 0x100071636?)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/baseapp/abci.go:73 +0x559
github.com/tendermint/tendermint/internal/proxy.(*proxyClient).InitChain(0xc00019cf50, {0x1031b5960, 0xc0000bc910}, 0xc0004e5740?)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.3/internal/proxy/client.go:129 +0x16e
github.com/tendermint/tendermint/internal/consensus.(*Handshaker).ReplayBlocks(, {_, }, {{{0xb, 0x0}, {0xc00014f350, 0x11}}, {0xc000988e50, 0x9}, 0x1, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.3/internal/consensus/replay.go:312 +0xf45
github.com/tendermint/tendermint/internal/consensus.(*Handshaker).Handshake(0xc000b2fd18, {0x1031b5960, 0xc0000bc910}, {0x1031d7b40?, 0xc00019cf50?})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.3/internal/consensus/replay.go:268 +0x3db
github.com/tendermint/tendermint/node.(*nodeImpl).OnStart(0xc0006eb500, {0x1031b5960, 0xc0000bc910})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.3/node/node.go:510 +0x2d5
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc0006eb500, {0x1031b5960?, 0xc0000bc910})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.3.3/libs/service/service.go:117 +0x203
github.com/cosmos/cosmos-sdk/server.startInProcess(, {{0x0, 0x0, 0x0}, {0x1031de4f0, 0xc000947770}, {0xc0009d4b90, 0x9}, {0x1031bd528, 0xc00033e680}, ...}, ...)
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/server/start.go:402 +0x967
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000303b00?, {0x104803f20?, 0x0?, 0x0?})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/server/start.go:207 +0x8d9
github.com/spf13/cobra.(*Command).execute(0xc0001d8900, {0x104803f20, 0x0, 0x0})
/Users/macbookpro/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000445500)
/Users/macbookpro/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
/Users/macbookpro/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
/Users/macbookpro/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x1046e6538?, {0xc000412738, 0x16})
/Users/macbookpro/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.3.13/server/cmd/execute.go:35 +0x145
main.main()
/Users/macbookpro/go/src/github.com/sei-protocol/sei-chain/cmd/seid/main.go:16 +0x2b

**Comment by philipsu522** [comment]
can you try running with https://www.docs.sei.io/dev-node/quickstart and letting us knowif you still have issues?

**Comment by philipsu522** [comment]
closing for now, feel free to reopen
