### ISSUE TITLE
[Misc] Getting weird error when submitting simple transaction on Testnet using web3auth social accounts

### ISSUE THREAD

**Issue by andreyluiz** [sei-protocol/sei-chain#1730]
**Seid version**
Not applicable.

**Chain ID**
0x530 (TestNet)

**Describe the Issue**
I'm developing an application on Sei for one of my clients, and currently, I'm testing it with Testnet. The application is a dApp using web3auth for authentication using Metamask and Social Media.

I'm trying first with a simple transaction sending 1 Sei from my account to myself. Using Metamask, the transaction works fine. But when I try to use the social media accounts, the call fails with:

```
Error: Cannot convert string to Uint8Array. toBytes only supports 0x-prefixed hex strings and this string was given: 0xNaN
```

As you see, this is an error that is happening on the JavaScript side, when calling the RPC. The transaction is not even submitted (I can't see it on the network tab of the browser). And of course, I'm not sending 0xNaN anywhere.

Of course, my first impulse was to reach out to web3auth and check with them if they had something to say because it works with Metamask and fails on socials. They had no clue why the error happened.

So I tried testing with another Testnet (a local one, and Goerli), and the transaction works.

So my eyes turn again to Sei. 

I have no idea why the error happens, and why other Testnets work fine.

Could you guys help me?

**Additional context**
![Screenshot 2024-06-12 at 09 58 20](https://github.com/sei-protocol/sei-chain/assets/1965897/33d58236-78d5-473f-b3dd-68164a3754f2)

Here's a test I made using the first Metamask (refer to the image), and the transaction is fulfilled. There is the hash of the tx. Then I disconnect and connect the social wallet, and when repeating the same transaction, the error happens.

```ts
export const send = async (amountStr: string) => {
  const provider = new ethers.providers.Web3Provider(
    web3auth.provider as ethers.providers.ExternalProvider
  );
  const signer = provider.getSigner();
  const amount = ethers.utils.parseEther(amountStr);

  const fromAddress = await signer.getAddress();
  const toAddress = fromAddress;

  const transaction = {
    from: fromAddress,
    to: toAddress,
    data: '0x',
    nonce: await provider.getTransactionCount(fromAddress),
    value: amount
  };

  const gas = await provider.estimateGas(transaction as any);

  console.log('sending transaction', gas.toString());
  const tx = await signer.sendTransaction(transaction);

  console.log(tx.hash);

  await tx.wait();
};
```

And this is the function I'm using to produce the log above.

**Comment by philipsu522** [comment]
looks like in the logs you're supply `0xNaN` as you said - did you verify the signer is correct?

**Comment by philipsu522** [comment]
closing for now, feel free to reopen if you're still having issues
