### ISSUE TITLE
Native sei chain have error rising related to gas fee and gas limit

### ISSUE THREAD

**Issue by zenoUsman** [sei-protocol/sei-chain#1803]
**Seid version**
V5.7.2

**Chain ID**
Pacific 

**Description**
Before 5.7.2 update the mint functions in nft contract perfectly work on default gas limit 200000 and gas fee "0.15usei", after this update the mint function rising the error of gas estimation incorrectly error showing: "Error: Broadcasting transaction failed with code 13 (codespace: sdk). Log: insufficient fees; got: 9842usei required: 49206usei: insufficient fee
    at n.broadcastTx (main.733897c1.js:2:77090)
    at async n.executeMultiple (main.733897c1.js:2:93844)
    at async onClick (main.733897c1.js:2:5327230)" all js library having same issue please give us the solution of it.

**Expected behavior**
Firstly it's rising with compass wallet now all wallets approving transaction of nft mint but default gas limit behavior is rising error. By seiscan  error 1 is rising because they using auto fee adjustment.

**screenshots**
![error](https://github.com/user-attachments/assets/2bb53e28-b787-4067-bad9-6e1973883249)
![error1](https://github.com/user-attachments/assets/44b7c24f-02df-4fde-9412-327cdde86e4d)

**Additional context**
Please give us details if default gas fee is changed or we need to increase how much gas limit for successful transaction I increased it to 0.05sei per transaction but not approving.

**Example transaction error**
https://seitrace.com/tx/E769D0AD479F162A7ABE1A2927301EBE3A7D9BEE26BC18EC15B967E78BFC48CB?chain=pacific-1

**Comment by philipsu522** [comment]
hey @zenoUsman do you have an example tx?

**Comment by zenoUsman** [comment]
****

> hey @zenoUsman do you have an example tx?

Already attached 

https://seitrace.com/tx/E769D0AD479F162A7ABE1A2927301EBE3A7D9BEE26BC18EC15B967E78BFC48CB?chain=pacific-1

**Comment by philipsu522** [comment]
@zenoUsman thanks! Gas changes have not been made on the CW side. Taking a look at some other txs interacting with the same contract:
- https://seitrace.com/tx/10CC2B5A702437D42687872B6F42EB860CF5725E5225A241269DB5B5EBADB0E2?chain=pacific-1
- https://seitrace.com/tx/09C65381B23B1B9BA996A59D2D05E660B66198E79624221A32ECD0A7AC0371EE?chain=pacific-1
- https://seitrace.com/tx/6E1FB7454AB96050E8BC1A88FE9D2918D61393C9181E91B0E2174FCD1B3086B7?chain=pacific-1

Looks like yo'ure only supplying 280k gas, while these are use ~600k gas. One thing to note that is you seem to also set a gas price about 10x higher than others, i.e.
0.00000020132504879403 vs
0.00000003060083915156

So you should 3x increase your gas but 10x decrease gas prices and this should work. Please give this a shot and let me know if it works

**Comment by zenoUsman** [comment]
I figured out its wallets default rpc error most wallet using polkachu rpc I thinks it's not updated I used rhinostake RPC estimation is correctly work, the estimate cost on mint nft transaction is 0.09Sei while before that it's cost higher UpTo 0.2sei it's suggested which lead to mint error.
