### ISSUE TITLE
[BUG] Build failing with go version 1.23 

### ISSUE THREAD

**Issue by aychocho** [sei-protocol/sei-chain#1902]
**Seid version**

This bug happens when installing/building v4.1.4-evm-devnet

**Bug description**

Attempting to run 

`make install`

while utilizing Go version 1.23 throws the following error

```
link: github.com/fjl/memsize: invalid reference to runtime.stopTheWorld
make: *** [Makefile:69: install] Error 1 

```

This appears to be a known issue with the memsize package, checking the memsize README might provide a solution: 

> NOTE: As of Go 1.23, memsize no longer works because of a restriction added by the
> Go toolchain. The Go 1.23 compiler no longer allows access to runtime symbols via
> go:linkname, which prevents memsize from accessing the Stop-the-World
> functionality of the Go runtime.
> 
> If your program depends on memsize, you can disable the restriction when building
> your program:
> 
>     go build -ldflags=-checklinkname=0

**To Reproduce**
1. Run make install within sei-chain whilst Go 1.23 is installed

**Additional context**

Building with Go version 1.22.8 works fine

**Comment by cordt-sei** [comment]
It's a known issue.

_Originally posted by @fjl in https://github.com/ethereum/go-ethereum/issues/30100#issuecomment-2205674730_

**Comment by galaxy-tbehrens** [comment]
I suggest to re-open this. It's easily fixed by applying the upstream patch: https://github.com/ethereum/go-ethereum/commit/e4675771eda550e7eeb63a8884816982c1980644
