### ISSUE TITLE
[BUG] eth_getLogs returns empty for transaction 0x849a6ceaf4ce0b9781c9e299fd15d2094b79a29c54bd175acf7af7101e9e3fc1

### ISSUE THREAD

**Issue by quick-pawiromitchel** [sei-protocol/sei-chain#1934]
**Seid version**
```
name: sei
server_name: <appd>
version: v5.9.0-hotfix-3
commit: 95532966c643e9e965fdd9aff8002899b3c5920a
build_tags: netgo,
go: go version go1.21.13 linux/amd64
build_deps:
- cosmossdk.io/errors@v1.0.0
- filippo.io/edwards25519@v1.0.0-rc.1
- github.com/99designs/keyring@v1.2.1
```

**Chain ID**
Pacific

**Describe the bug**
Logs aren't returned, node returns empty
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": []
}
```

But the explorer shows 28 logs
- https://seistream.app/transactions/0x849a6ceaf4ce0b9781c9e299fd15d2094b79a29c54bd175acf7af7101e9e3fc1?tab=logs
- https://seitrace.com/tx/0x849a6ceaf4ce0b9781c9e299fd15d2094b79a29c54bd175acf7af7101e9e3fc1?chain=pacific-1&tab=logs

**To Reproduce**
Run the following payload `{"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"fromBlock":"0x6703ac6","toBlock":"0x6703ac6"}]}`

**Expected behavior**
I expect logs to show up

**Comment by cordt-sei** [comment]
Try this one

`'{"jsonrpc":"2.0","id":1,"method":"sei_getLogs","params":[{"fromBlock":"0x6703ac6","toBlock":"0x6703ac6"}]}'`

**Comment by AlexBHarley** [comment]
We've just run into this, a little annoying to special case when using tools like Viem.

Any reason it doesn't work with eth_getLogs as we'd expect?

**Comment by philipsu522** [comment]
Fixed in https://github.com/sei-protocol/sei-chain/pull/1941
