### ISSUE TITLE
cant start

### ISSUE THREAD

**Issue by zhangsj** [sei-protocol/sei-chain#232]
Sep 02 15:35:40 dash seid[3054979]: 3:35PM INF Starting EventBus service impl=EventBus module=events
Sep 02 15:35:40 dash seid[3054979]: 3:35PM INF Starting PubSub service impl=PubSub module=pubsub
Sep 02 15:35:40 dash seid[3054979]: 3:35PM INF Starting IndexerService service impl=IndexerService module=txindex
Sep 02 15:35:40 dash seid[3054979]: 3:35PM INF ABCI Handshake App Info hash="\r\rE�Uu�Ll!�y���)�a��V\x1f{�\u007f@�p\r���" height=695724 module=consensus protocol-version=0 software-version=1.1.2beta-internal-6-gc09155c
Sep 02 15:35:40 dash seid[3054979]: 3:35PM INF ABCI Replay Blocks appHeight=695724 module=consensus stateHeight=695724 storeHeight=695725
Sep 02 15:35:40 dash seid[3054979]: 3:35PM INF Replay last block using real app module=consensus
Sep 02 15:35:40 dash seid[3054979]: 3:35PM INF Current block time 2022-07-20 07:47:11.050272005 +0000 UTC, last 2022-07-20 07:46:56.616581218 +0000 UTC; duration 60000000000
Sep 02 15:35:43 dash seid[3054979]: panic: more validators than maxValidators found [recovered]
Sep 02 15:35:43 dash seid[3054979]:         panic: more validators than maxValidators found
Sep 02 15:35:43 dash seid[3054979]: goroutine 1 [running]:
Sep 02 15:35:43 dash seid[3054979]: go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.6.3/trace/span.go:359 +0x2a
Sep 02 15:35:43 dash seid[3054979]: go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000effe00, {0x0, 0x0, 0x36597e0?})
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.6.3/trace/span.go:398 +0x8dd
Sep 02 15:35:43 dash seid[3054979]: panic({0x1aedc00, 0x273d3a0})
Sep 02 15:35:43 dash seid[3054979]:         /usr/local/go/src/runtime/panic.go:838 +0x207
Sep 02 15:35:43 dash seid[3054979]: github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.GetLastValidators({{0x2748af8, 0xc001c95c90}, {0x276b398, 0xc001c819c0}, {0x2761a80, 0xc000f2af30}, {0x7f6911c1d0f8, 0xc0005222c0}, {0x276b250, 0xc000f291a0}, ...}, ...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/staking/keeper/validator.go:316 +0x511
Sep 02 15:35:43 dash seid[3054979]: github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.TrackHistoricalInfo({{0x2748af8, 0xc001c95c90}, {0x276b398, 0xc001c819c0}, {0x2761a80, 0xc000f2af30}, {0x7f6911c1d0f8, 0xc0005222c0}, {0x276b250, 0xc000f291a0}, ...}, ...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/staking/keeper/historical_info.go:93 +0x358
Sep 02 15:35:43 dash seid[3054979]: github.com/cosmos/cosmos-sdk/x/staking.BeginBlocker({{0x275e428, 0xc000052070}, {0x276cbc0, 0xc0067a5a80}, {{0xb, 0x0}, {0xc005e28160, 0xa}, 0xa9dad, {0x2ff1705, ...}, ...}, ...}, ...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/staking/abci.go:19 +0x118
Sep 02 15:35:43 dash seid[3054979]: github.com/cosmos/cosmos-sdk/x/staking.AppModule.BeginBlock(...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/staking/module.go:168
Sep 02 15:35:43 dash seid[3054979]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x275e428, 0xc000052070}, {0x276cbc0, 0xc0067a5a80}, {{0xb, 0x0}, {0xc005e28160, 0xa}, 0xa9dad, ...}, ...}, ...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:479 +0x3a2
Sep 02 15:35:43 dash seid[3054979]: github.com/sei-protocol/sei-chain/app.(*App).BeginBlocker(_, {{0x275e428, 0xc000052070}, {0x276cbc0, 0xc0067a5a80}, {{0xb, 0x0}, {0xc005e28160, 0xa}, 0xa9dad, ...}, ...}, ...)
Sep 02 15:35:43 dash seid[3054979]:         /opt/test/sei-chain/sei-chain/app/app.go:782 +0x85
Sep 02 15:35:43 dash seid[3054979]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc0067a2e00, 0x20, 0x20}, {{0xb, 0x0}, {0xc005e28160, 0xa}, 0xa9dad, {0x2ff1705, ...}, ...}, ...})
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:194 +0x97c
Sep 02 15:35:43 dash seid[3054979]: github.com/sei-protocol/sei-chain/app.(*App).BeginBlock(_, {{0xc0067a2e00, 0x20, 0x20}, {{0xb, 0x0}, {0xc005e28160, 0xa}, 0xa9dad, {0x2ff1705, ...}, ...}, ...})
Sep 02 15:35:43 dash seid[3054979]:         /opt/test/sei-chain/sei-chain/app/abci.go:17 +0x3a5
Sep 02 15:35:43 dash seid[3054979]: github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc0067a2e00, 0x20, 0x20}, {{0xb, 0x0}, {0xc005e28160, 0xa}, 0xa9dad, {0x2ff1705, ...}, ...}, ...})
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:280 +0x118
Sep 02 15:35:43 dash seid[3054979]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc0067a2e00, 0x20, 0x20}, {{0xb, 0x0}, {0xc005e28160, 0xa}, 0xa9dad, {0x2ff1705, ...}, ...}, ...})
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:81 +0x55
Sep 02 15:35:43 dash seid[3054979]: github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x275f538?, 0xc00d216cc0}, {0x2765b60, 0xc005f363b0}, 0xc005e7e000, {0x276bcc8, 0xc005eab740}, 0xa9dac?)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:307 +0x3dd
Sep 02 15:35:43 dash seid[3054979]: github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc005ea7ab0, 0x7}}, {0xc005ea7ac0, 0xa}, 0x1, 0xa9dac, {{0xc005ca1fe0, ...}, ...}, ...}, ...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:140 +0x171
Sep 02 15:35:43 dash seid[3054979]: github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc005ea7ab0, 0x7}}, {0xc005ea7ac0, 0xa}, 0x1, 0xa9dac, {{0xc005ca1fe0, ...}, ...}, ...}, ...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:503 +0x23c
Sep 02 15:35:43 dash seid[3054979]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc005ea7ab0, 0x7}}, {0xc005ea7ac0, 0xa}, 0x1, 0xa9dac, {{0xc005ca1fe0, ...}, ...}, ...}, ...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:416 +0x7ae
Sep 02 15:35:43 dash seid[3054979]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc002329fd0, {0x276d530, 0xc00115ef70})
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
Sep 02 15:35:43 dash seid[3054979]: github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc005ea7ab0, 0x7}}, {0xc005ea7ac0, 0xa}, 0x1, 0xa9dac, ...}, ...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
Sep 02 15:35:43 dash seid[3054979]: github.com/tendermint/tendermint/node.NewNode(0xc00051ea00, {0x275b200, 0xc0002174a0}, 0xc00234eef0, {0x27436c0, 0xc005335bf0}, 0x0?, 0x0?, 0xc00234f110, {0x275f538, ...}, ...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
Sep 02 15:35:43 dash seid[3054979]: github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2773f78, 0xc000149f80}, {0x0, 0x0}, {0x2763518, 0xc000da8720}, ...}, ...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7db
Sep 02 15:35:43 dash seid[3054979]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0012e4000?, {0xc00011d760?, 0x0?, 0x2?})
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169
Sep 02 15:35:43 dash seid[3054979]: github.com/spf13/cobra.(*Command).execute(0xc0012e4000, {0xc00011d720, 0x2, 0x2})
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
Sep 02 15:35:43 dash seid[3054979]: github.com/spf13/cobra.(*Command).ExecuteC(0xc000d84c80)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
Sep 02 15:35:43 dash seid[3054979]: github.com/spf13/cobra.(*Command).Execute(...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
Sep 02 15:35:43 dash seid[3054979]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
Sep 02 15:35:43 dash seid[3054979]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc000da6530, 0xa})
Sep 02 15:35:43 dash seid[3054979]:         /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
Sep 02 15:35:43 dash seid[3054979]: main.main()
Sep 02 15:35:43 dash seid[3054979]:         /opt/test/sei-chain/sei-chain/cmd/seid/main.go:16 +0x31
Sep 02 15:35:43 dash systemd[1]: seid.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 02 15:35:43 dash systemd[1]: seid.service: Failed with result 'exit-code'.
Sep 02 15:35:47 dash systemd[1]: seid.service: Scheduled restart job, restart counter is at 1.

**Comment by wade-liwei** [comment]
你的微信是多少？
咱们一起研究。 我能跑起来

**Comment by philipsu522** [comment]
Sorry for the late response, but these issues should be fixed now in the latest version - **2.0.47beta**
