### ISSUE TITLE
deploy  spot-lite  contract 

### ISSUE THREAD

**Issue by wade-liwei** [sei-protocol/sei-chain#234]
hello, developer

I deploy the  contract: https://github.com/sei-protocol/spot-lite

place order, get the errors: has no ticksize configured

I check the gov proposals:

- content:
    '@type': /seiprotocol.seichain.dex.RegisterPairsProposal
    batchcontractpair:
    - contractAddr: sei14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sh9m79m
      pairs:
      - assetDenom: uatom
        priceDenom: uusdc
        ticksize: "0.000000100000000000"
      - assetDenom: ubtc
        priceDenom: uusdc
        ticksize: "0.000000100000000000"
      - assetDenom: ueth
        priceDenom: uusdc
        ticksize: "0.000000100000000000"
      - assetDenom: uosmo
        priceDenom: uusdc
        ticksize: "0.000000100000000000"
      - assetDenom: usol
        priceDenom: uusdc
        ticksize: "0.000000100000000000"
      - assetDenom: usei
        priceDenom: uusdc
        ticksize: "0.000000100000000000"
    description: Register initial pairs for Spot
    title: Register initial pairs for Spot
  deposit_end_time: "2022-09-05T06:25:34.193459312Z"
  final_tally_result:
    abstain: "0"
    "no": "0"
    no_with_veto: "0"
    "yes": "0"
  proposal_id: "2"
  status: PROPOSAL_STATUS_VOTING_PERIOD
  submit_time: "2022-09-03T06:25:34.193459312Z"
  total_deposit:
  - amount: "10011000000"
    denom: usei
  voting_end_time: "2022-09-05T06:26:46.809753086Z"
  voting_start_time: "2022-09-03T06:26:46.809753086Z"
  
  
  
  try the cmds, but does not work.
  
seid tx gov weighted-vote 2 yes -y --from=admin --chain-id=sei-chain --fees=2000usei --gas=500000 --broadcast-mode=block

seid tx gov vote 2 yes -y --from=admin --chain-id=sei-chain --fees=2000usei --gas=500000 --broadcast-mode=block

**Comment by Kbhat1** [comment]
Sorry for the late response, but register pair is now a transaction not a proposal on latest master https://github.com/sei-protocol/sei-chain/blob/master/x/dex/client/cli/tx/tx_register_pairs.go. Please try again. Closing this out for now but feel free to reopen
