### ISSUE TITLE
Unknown field "max_wasm_code_size"

### ISSUE THREAD

**Issue by Paithe** [sei-protocol/sei-chain#28]
When installing 1.0.1beta from scratch, you get a 

`panic: unknown field "max_wasm_code_size" in types.Params`

I'm using this genesis.json: https://raw.githubusercontent.com/sei-protocol/testnet/master/sei-testnet-1/genesis.json

**Comment by philipsu522** [comment]
This should be fixed now in https://github.com/sei-protocol/testnet/pull/10
@Paithe can you confirm?

**Comment by Paithe** [comment]
Now getting: `panic: invalid Bech32 prefix; expected sei, got cosmos`

Do you need the full trace?

**Comment by philipsu522** [comment]
You should be using v1.0.1beta and not master - are you building your seid binary off of master?

**Comment by Paithe** [comment]
Yes I built with main, I didn't expect the fix in the same release. The code size error is gone, getting `wrong Block.Header.AppHash` on the first block now.

Do you want me to create a new issue for this, as the initial error is fixed?

**Comment by philipsu522** [comment]
This is fixed now @Paithe sorry for the late response! We're currently on **2.0.47beta** in sei-devnet-3 and atlantic-2
