### ISSUE TITLE
Discord invitation link is invalid or expired

### ISSUE THREAD

**Issue by josedev-union** [sei-protocol/sei-chain#374]
I am trying to add a validator node by following this guide https://docs.seinetwork.io/nodes-and-validators/seinami-incentivized-testnet/joining-incentivized-testnet#2.-send-funds-to-your-account.
I tried to open discord link but it is not working.
https://discord.gg/YpYQ77Db
![image](https://user-images.githubusercontent.com/70741025/200053687-26243f3c-3010-40c3-b66e-0ed4a5586a21.png)

Can you please update the invitation link so I can join?

**Comment by philipsu522** [comment]
Hey! Please try https://discord.com/invite/sei
