### ISSUE TITLE
peer for error

### ISSUE THREAD

**Issue by Penton7** [sei-protocol/sei-chain#38]
Hey, I’m trying to run and sync with your network, but when I run it in the logs, it says the following:
`2:39PM INF Starting Peer service impl="Peer{MConn{135.181.249.17:26656} 07536775a07378711a9e8e772fbba231cbe72e4d out}" module=p2p peer={"id":"07536775a07378711a9e8e772fbba231cbe72e4d","ip":"135.181.249.17","port":26656}
2:39PM INF Starting MConnection service impl=MConn{135.181.249.17:26656} module=p2p peer={"id":"07536775a07378711a9e8e772fbba231cbe72e4d","ip":"135.181.249.17","port":26656}
2:39PM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
2:39PM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"07536775a07378711a9e8e772fbba231cbe72e4d","ip":"135.181.249.17","port":26656}
2:39PM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"07536775a07378711a9e8e772fbba231cbe72e4d","ip":"135.181.249.17","port":26656}
2:39PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
2:39PM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"07536775a07378711a9e8e772fbba231cbe72e4d","ip":"1
35.181.249.17","port":26656}
`

<img width="1416" alt="Screenshot at Jun 10 15-40-13" src="https://user-images.githubusercontent.com/47526333/173066146-5e3da9d9-6824-4114-88ab-a43a65d00aa8.png">

**Comment by chalabi2** [comment]
Peer errors are normal, you should try updating the peers list in the `config.toml` or downloading the new address book located here `https://github.com/sei-protocol/testnet/blob/main/sei-testnet-2/addrbook.json`
