### ISSUE TITLE
Cannot make install on mac m1

### ISSUE THREAD

**Issue by Puckapao** [sei-protocol/sei-chain#391]
Terminal is checked with 'Open with Rosetta'
Cannot 'make install' with any branches

This is the error.
`# github.com/zondax/hid
In file included from ../go/pkg/mod/github.com/zondax/hid@v0.9.0/hid_enabled.go:38:
../go/pkg/mod/github.com/zondax/hid@v0.9.0/hidapi/mac/hid.c:693:34: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:133:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here`

**Comment by philipsu522** [comment]
This is fixed now, thanks!

**Comment by velikanghost** [comment]
Make install still returns same issue on M1, tried almost all the release

**Comment by leonip123** [comment]
I resolve the above issue by updating the package dependency from hid@v0.9.0 to hid@v0.9.1.
`go get github.com/zondax/hid@v0.9.1`

Then, I run `make install` and it is shown
`go install -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=sei -X github.com/cosmos/cosmos-sdk/version.ServerName=seid -X github.com/cosmos/cosmos-sdk/version.Version=3.0.1-113-g1eb2485d -X github.com/cosmos/cosmos-sdk/version.Commit=1eb2485da967f1d26f0f81f442094da3b7ed5dd4 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo ledger,"' ./cmd/seid`

However, `Make install` still not work.
