### ISSUE TITLE
I started the node with 1.2.2beta-postfix, but did not start synchronizing the data.

### ISSUE THREAD

**Issue by COLUD4** [sei-protocol/sei-chain#429]
seid status
{"NodeInfo":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"7599dc77fd9b41d469cf1214ea71619cfca89daa","listen_addr":"tcp://0.0.0.0:26656","network":"atlantic-1","version":"0.34.19","channels":"40202122233038606100","moniker":"sei","other":{"tx_index":"on","rpc_address":"tcp://127.0.0.1:26657"}},"SyncInfo":{"latest_block_hash":"","latest_app_hash":"","latest_block_height":"0","latest_block_time":"1970-01-01T00:00:00Z","earliest_block_hash":"","earliest_app_hash":"","earliest_block_height":"0","earliest_block_time":"1970-01-01T00:00:00Z","catching_up":true},"ValidatorInfo":{"Address":"2666FE7598BC3BEE6F4BD55ED0036C1E3E062DD7","PubKey":{"type":"tendermint/PubKeyEd25519","value":"Vgjar7wEDvFOu78cftfpzHzxGCMP9RX/wAL27Mxi67Y="},"VotingPower":"0"}}

**Comment by aidan452** [comment]
your problem solved?

**Comment by alanwilhelm** [comment]
I'm getting 

`panic: unknown field "reduction_period_in_epochs" in types.Params`

while starting 1.2.2beta-postfix for the first time

go 1.19 (is this the issue?)

**Comment by BrandonWeng** [comment]
Where did you get the genesis file from? Also, it’s worth noting that we recommend users to develop and test with atlantic-2 going forward (using version 2.0.47beta)

 Docs for joining https://docs.seinetwork.io/
