### ISSUE TITLE
Can not deploy contract

### ISSUE THREAD

**Issue by kiennd** [sei-protocol/sei-chain#430]
Dear Sei Team,
I got an issue when deploy the contract to atlantic-1 tesnet:
`failed to execute message; message index: 0: can not create code: unauthorized`

`code: 4
codespace: sdk
data: ""
events:
- attributes:
  - index: false
    key: c3BlbmRlcg==
    value: c2VpMWU5NnA0cGpqYTlnM2poeTc5NDZjM2xwOXg1cG5kdjdkZmZ2a2Vw
  - index: false
    key: YW1vdW50
    value: MTAwMHVzZWk=
  type: coin_spent
- attributes:
  - index: false
    key: cmVjZWl2ZXI=
    value: c2VpMTd4cGZ2YWttMmFtZzk2MnlsczZmODR6M2tlbGw4YzVsYTRqa2R1
  - index: false
    key: YW1vdW50
    value: MTAwMHVzZWk=
  type: coin_received
- attributes:
  - index: false
    key: cmVjaXBpZW50
    value: c2VpMTd4cGZ2YWttMmFtZzk2MnlsczZmODR6M2tlbGw4YzVsYTRqa2R1
  - index: false
    key: c2VuZGVy
    value: c2VpMWU5NnA0cGpqYTlnM2poeTc5NDZjM2xwOXg1cG5kdjdkZmZ2a2Vw
  - index: false
    key: YW1vdW50
    value: MTAwMHVzZWk=
  type: transfer
- attributes:
  - index: false
    key: c2VuZGVy
    value: c2VpMWU5NnA0cGpqYTlnM2poeTc5NDZjM2xwOXg1cG5kdjdkZmZ2a2Vw
  type: message
- attributes:
  - index: false
    key: ZmVl
    value: MTAwMHVzZWk=
  type: tx
- attributes:
  - index: false
    key: YWNjX3NlcQ==
    value: c2VpMWU5NnA0cGpqYTlnM2poeTc5NDZjM2xwOXg1cG5kdjdkZmZ2a2VwLzIyMQ==
  type: tx
- attributes:
  - index: false
    key: c2lnbmF0dXJl
    value: RzRzblRsWW12WElPaEQ4dkNySUtPZERRRllzSlFqME45TlpNRGJJeW5ac0lUSE1ycm44Um43eFo1d3E1UmdJdFRRN2R6Y1pmUEJwWVRTTDhoUFhUalE9PQ==
  type: tx
gas_used: "571041"
gas_wanted: "571041"
height: "12434534"
info: ""
logs: []
raw_log: 'failed to execute message; message index: 0: can not create code: unauthorized'
timestamp: ""
tx: null
txhash: E1A4A13D5CE9F9C5E0FD0D85AB5F8085BA1DB6E12C6AF3163D47313BEB6B4117`

**Comment by floki63** [comment]
Please can you help with how you deploy contract on the sei network?

**Comment by BrandonWeng** [comment]
@floki63 alrantic 1 is a permissions chain, contracts are deployed throguh governance. what’s the command you’re running? 

atlantic-2 is permissionless and it’s the recommended chain for testing and development instructions to join https://docs.seinetwork.io/
