### ISSUE TITLE
can't sign by ledger through keplr

### ISSUE THREAD

**Issue by Kwaskoff** [sei-protocol/sei-chain#449]
![Screenshot from 2022-12-07 00-48-44](https://user-images.githubusercontent.com/15308024/206050705-7a394df3-c79a-4d52-8c8a-25b1e4559894.png)
every app just open keplr and after push button "approve" - this message, ledger not say anything 

Keplr 0.11.13, Ledger Nano S

**Comment by besated** [comment]
Hey! This seems to be an issue with the front-end client. What app are you trying to use your ledger on? Ledgers only support Amino signing, so when getting the offline signer for Ledgers, you must specify `getOfflineSignerAuto` to get the appropriate `OfflineSigner`.
