### ISSUE TITLE
Cannot start 1.2.2beta-postfix - error unknown field "reduction_period_in_epochs" in types.Params

### ISSUE THREAD

**Issue by alanwilhelm** [sei-protocol/sei-chain#478]
I'm getting this error on first run. I'm pretty sure I have the right genesis and addrbook files.

Ubuntu LTS
Go 1.19

`seid start`

<img width="621" alt="image" src="https://user-images.githubusercontent.com/175353/210664648-6cc9933c-8ca4-4a80-b14b-e2d3445d594a.png">

**Comment by philipsu522** [comment]
Hey! Sorry for the late response - this should be fixed in the latest version - **2.0.47beta**
