### ISSUE TITLE
can't mint nor gift

### ISSUE THREAD

**Issue by Spardanian** [sei-protocol/sei-chain#677]
hello,
I have done more than 25 txs days ago and I still can't gift any sunken treasure, it keeps telling me to do 25 txs.
I also received a gift, but I can't mint it, it keeps giving me errors.
sei1gp4pk30umm8ss363vs7zxstep57hcd3pvl0qgs
![image](https://user-images.githubusercontent.com/128751967/228967843-af4b8b77-8e1c-4b95-8987-f8fc36082b56.png)
![image](https://user-images.githubusercontent.com/128751967/228967870-7a76d4de-50b5-43d9-a59d-22bbf7daeeb4.png)

**Comment by Abozar55** [comment]
Love this pic 😍 perfect 👍🏼
