### ISSUE TITLE
Question: who will pay the gas of hook functions

### ISSUE THREAD

**Issue by xiaozzz** [sei-protocol/sei-chain#697]
i find that the chain will call hooks during `EndBlockerAtomic `. but who should pay the gas fee?
is the contract deployer or someone pay the gas? 
what happen if there's a inf loop in hook functions?
what happen if the payer is out of gas?

**Comment by BrandonWeng** [comment]
The begin/end block hooks were removed in this PR: https://github.com/sei-protocol/sei-chain/pull/666 

Feel free to reopen if you have additional questions
