### ISSUE TITLE
Seeing more peers connected than the max-connections configured

### ISSUE THREAD

**Issue by BrandonWeng** [sei-protocol/sei-chain#748]
curl -sS http://localhost:26657/net_info | jq -r '.n_peers' gives 180 peers although

max-connections = 100 in the config.toml 

This happens after restarting sei service for second time after fresh statesync

Version: `2.0.44beta`

**Comment by theBro-cros-nest** [comment]
the peer amount reported under net_info does not reflect to connected peers. Prometheus reports 83 peers for my node when net_info reports 144. And looking at established TCP connections, it is clear that net_info is wrong. Established connections in my case includes some RPC, prometheus and remote signer sockets, so prometheus appears to be pretty accurate.
```
$ curl -sS http://localhost:26657/net_info | jq -r '.n_peers'
144
$ curl -sS 0:26660/metrics | grep peers\{
tendermint_p2p_peers{chain_id="atlantic-2"} 83
$ sudo ss -natup|grep ESTA.*seid|wc -l
89
```

**Comment by BrandonWeng** [comment]
- default is 300, if you add all the peers then it will exceed the limit

**Comment by yzang2019** [comment]
@theBro-cros-nest net_info reflect all the peers identified by this node, so it does include both healthy and unhealthy peers. Would suggest bump max connections to mitigate this issue
