### ISSUE TITLE
panic: assignment to entry in nil map in p2p module

### ISSUE THREAD

**Issue by BrandonWeng** [sei-protocol/sei-chain#749]
panic: assignment to entry in nil map

goroutine 968 [running]:
github.com/tendermint/tendermint/internal/p2p.(*PeerManager).Add(0xc0002b8000, {{0xc0d0557928, 0x28}, {0xc0d0557920, 0x5}, {0xc0d0557951, 0x1b}, 0x777d, {0x0, 0x0}})
        /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.2.4/internal/p2p/peermanager.go:435 +0x505

**Comment by philipsu522** [comment]
Fixed in https://github.com/sei-protocol/sei-tendermint/pull/134
