### ISSUE TITLE
Longer running validators w/ more disk usage results in poorer performance

### ISSUE THREAD

**Issue by BrandonWeng** [sei-protocol/sei-chain#751]
Longer running validators w/ more disk usage results in poorer performance

- running different configurations 
- pruning does affect performance 
- looking at other things to retain signing performance while pruning

**Comment by BrandonWeng** [comment]
- testing with RAIDED disks but unlikeyl to see performance improvements
- Periodically staetsyncing is the best way to keep your node performant 
- not much we can do right now, requires a large storage rewrite 
-

**Comment by mkaczanowski** [comment]
@BrandonWeng 
> testing with RAIDED disks but unlikeyl to see performance improvements

was there any improvement?
