### ISSUE TITLE
Excessive disk usage after dbsync 

### ISSUE THREAD

**Issue by BrandonWeng** [sei-protocol/sei-chain#752]
Disk usage after db-sync is quite excessive. Even with aggressive pruning, the chain consumes close to 3-4GB per hour, almost all going to application.db

**Comment by yzang2019** [comment]
The recommended mitigation for disk filling up issue after db sync is to use aggressive pruning + force compaction:
If you are on 2.0.47beta or later version, set the following configs in app.toml:

sed -i.bak -e 's/pruning = .*/pruning = "custom"/' /root/.sei/config/app.toml
sed -i.bak -e 's/pruning-keep-recent = .*/pruning-keep-recent = "1"/' /root/.sei/config/app.toml
sed -i.bak -e 's/pruning-keep-every = .*/pruning-keep-every = "0"/' /root/.sei/config/app.toml
sed -i.bak -e 's/pruning-interval = .*/pruning-interval = "1"/' /root/.sei/config/app.toml
sed -i.bak -e 's/compaction-interval = .*/compaction-interval = "60"/' /root/.sei/config/app.toml
