### ISSUE TITLE
Ledger integration issue

### ISSUE THREAD

**Issue by bjcd** [sei-protocol/sei-chain#774]
I have been using Sei with either Leap or Kepler, but in all occasions I was connected with a Ledger. 

While doing my tests I have realized that on many dapps, I was either:
- Encountering a "Data error" with Keplr before the Ledger prompts me to sign. 
- Or, with Leap, slightly different, the "Approve" button is not clickable. 

This occurs with many dapps, including the native Sei staking. On the attached image you will find all the dapps from the Sei Blockd quest where I'm encountering this exact same behavior. All the dapps that are not marked as "finished" are simply impossible to do with a Ledger device.

<img width="805" alt="Capture d’écran 2023-05-14 à 21 27 49" src="https://github.com/sei-protocol/sei-chain/assets/21067599/08206272-a9fd-4307-acb0-e94a5ceb3c18">

Staking on seinetwork . io is not possible either for the exact same reasons.

Steps to reproduce:
- Get a Ledger wallet
- Install the cosmos app
- Install Keplr and Leap
- On both Keplr and Leap, connect your Ledger wallet
- Go on seinetwork.io (or any other dapp related to unfinished missions on the screenshot attached)
- Stake (or interact)
- Experience "Data error" message on Keplr or disabled "Approve" button on Leap.

This is a major issue for Ledger users that should be looked at by the team. Don't fade. Thank you!

**Comment by philipsu522** [comment]
@bjcd let us know if you still have issues. We'll close this ticket for now given that there's a resolution

**Comment by bjcd** [comment]
Hello @philipsu522 @besated, thank you for the prompt feedback. The app from Mission 9 is now working, meaning that they probably have done the update that you are mentioning above. The other dapps (Missions 11, 6 and 7) as well as the seinetwork.io/stake dashboard are still not working.
