### ISSUE TITLE
invalid referance with whitepaper

### ISSUE THREAD

**Issue by snipeTR** [sei-protocol/sei-chain#775]
fig 5.1 and fig 5.2 etc not include whitepaper PDF
![image](https://github.com/sei-protocol/sei-chain/assets/31975916/fc087061-8e3f-45cd-aba7-f84b6f5709e8)
![image](https://github.com/sei-protocol/sei-chain/assets/31975916/ad9bcdea-46f8-4dd0-97d8-47de251ad6fd)
![image](https://github.com/sei-protocol/sei-chain/assets/31975916/2e5e3b88-bb05-407d-a29a-0188d649a0cc)

**Comment by Eko101089** [comment]
[Uploading proof-of-reserves-2.0.0.zip…]()

**Comment by lanqz46** [comment]
Pokonya mantap 👍

**Comment by philipsu522** [comment]
we've updated whitepaper
