### ISSUE TITLE
[BUG] Unable to access the database when restarting the node during DB sync

### ISSUE THREAD

**Issue by darron1217** [sei-protocol/sei-chain#783]
First of all, I appreciate the sei team's efforts to reduce operation overhead 👍 

**Seid version**
```
name: sei
server_name: <appd>
version: 2.0.48beta
commit: d6a3e606c7d3159e489d3499989f571cceca5fb6
build_tags: netgo,ledger
go: go version go1.20 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6
- github.com/CosmWasm/wasmd@v0.27.0 => github.com/sei-protocol/sei-wasmd@v0.0.1
```

**Chain ID**
`atlantic-2`

**Describe the bug**
I've encountered `failed to initialize database` error while restarting the node.
When unexpected exit happend while DB sync process, unable to restart DB sync process after. (expect resource cleaned up before prcoess goes down gracefully)

log command
`journalctl -u seid.service | grep -E "database|dbsync"`
logs
```
May 17 09:02:29 cosmovisor[1411964]: 9:02AM INF no file to sync; sync'ed 4431 out of 31231 so far; sleeping for 1.000000 seconds module=dbsync
May 17 09:02:30 cosmovisor[1411964]: 9:02AM INF no file to sync; sync'ed 4431 out of 31231 so far; sleeping for 1.000000 seconds module=dbsync
May 17 09:02:31 cosmovisor[1411964]: 9:02AM INF last metadata has timed out; sleeping for 1.000000 seconds module=dbsync
May 17 09:02:31 cosmovisor[1411964]: 9:02AM INF received metadata height=10416005 module=dbsync peer=6422161f9b769d19c9062c9e936a4d4487ac152b size=14143
--------- manual restart due to inactivity  ---------
May 17 09:09:24 cosmovisor[1411964]: 9:09AM INF stopping service module=dbsync service=DBSync
May 17 09:10:54 cosmovisor[1413357]: Error: failed to initialize database: database entry point either missing or corrupted
May 17 09:10:54 cosmovisor[1413357]:       --db-backend string                               database backend: goleveldb | cleveldb | boltdb | rocksdb | badgerdb (default "goleveldb")
May 17 09:10:54 cosmovisor[1413357]:       --db-dir string                                   database directory (default "data")
```

**To Reproduce**
1. Truncate `.sei/data` folder
2. Setup trust-height & trust-hash on `.sei/config/config.toml`
3. Run node
4. Restart it while db sync pending
5. See error

**Expected behavior**
The resources are gracefully cleaned up when restarting the node.

**Screenshots**
Logs are provided above

**Additional context**

**Comment by stadionlabel** [comment]
https://github.com/sei-protocol/sei-chain.git

**Comment by philipsu522** [comment]
@darron1217 this typically happens if db-sync is interrupted in the middle of loading files. One thing to note is that the exporter of the files will periodically shut down seid to create a new snapshot, at which time you (the importer) may see some stalls in file importing. Once the exporter is back up, things should proceed as normal. My suggestion here is to try again and wait a little longer before restarting. Let me know if this helps, and feel free to re-open if it does not.
