### ISSUE TITLE
Make build error

### ISSUE THREAD

**Issue by VegeBun-csj** [sei-protocol/sei-chain#798]
<img width="512" alt="image" src="https://github.com/sei-protocol/sei-chain/assets/39252213/a0c18d96-c002-44c3-8ec7-3f2b7d806eeb">

run `make build` at first when i clone the sei repo

**Comment by philipsu522** [comment]
@VegeBun-csj i seem to be unable to repro this. Can you try `make install` ?

**Comment by VegeBun-csj** [comment]
<img width="451" alt="image" src="https://github.com/sei-protocol/sei-chain/assets/39252213/6a124808-158a-4ece-af30-f9234e6f8e0e">

**Comment by VegeBun-csj** [comment]
Fixe with `apt-get install cmake gcc make`
