### ISSUE TITLE
Unable to join as a full node

### ISSUE THREAD

**Issue by LCyson** [sei-protocol/sei-chain#8]
Kept seeing this error when we tried to join as a full node:
`2:43PM ERR dialing failed (attempts: 7): auth failure: secret conn failed: read tcp 192.168.1.77:51422->3.22.112.181:26656: i/o timeout addr={"id":"27aab76f983cd7c6558f1dfc50b919daaef14555","ip":"3.22.112.181","port":26656} module=pex`

**Comment by philipsu522** [comment]
Also folks are trying to convert their nodes to validators and it seems to be failing silently. When run with broadcast mode=block they get 
```
Error: RPC error -32603 - Internal error: timed out waiting for tx to be included in a block
```

**Comment by LCyson** [comment]
Added a persistent node in the addrbook.json, people should be able to join as full node now.

**Comment by dylanschultzie** [comment]
> Also folks are trying to convert their nodes to validators and it seems to be failing silently. When run with broadcast mode=block they get
> 
> ```
> Error: RPC error -32603 - Internal error: timed out waiting for tx to be included in a block
> ```
> 
> Not sure if it's related, but both issues seem to start occurring around the same time

This is due to operators not adding `--fees` to their module, so the tx gets stuck in the mempool.

**Comment by philipsu522** [comment]
Yep, thanks. This was because faucet gave out too many funds. We've put faucet behind discord validation, so this is now resolved. Most txns are successful
