### ISSUE TITLE
[Question] panic: json: cannot unmarshal number 

### ISSUE THREAD

**Issue by victor0807** [sei-protocol/sei-chain#807]
**Seid version**
Show us output of `seid version --long | head`
3.0.1
**Chain ID**
Which chain are you running into issues with?
atlantic-2
**Describe the bug**

hello, i'm victor from south korea. please understand my poor english.
i still try to SEI NODE at my local and ec2 instance, but still there are error like this

when i start node like 
./seid start

panic: json: cannot unmarshal number 0.000000000000000000 into Go value of type uint64

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x1042f84b8?, {0x1400052a000?, 0x0?, 0x0?}, {0x1032ab990?, 0x14003e63440?})
	/Users/victor/go/pkg/mod/github.com/sei-protocol/sei-cosmos@v0.2.35/codec/proto_codec.go:176 +0x44
github.com/sei-protocol/sei-chain/x/mint.AppModule.InitGenesis({{{0x1032c53f8, 0x14000476280}}, {{0x1032c0bc0, 0x14000476280}, {0x10329a878, 0x140001cbd80}, {{0x1032c0bc0, 0x14000476280}, 0x14000586088, {0x10329a878, ...}, ...}, ...}, ...}, ...)
... still more

i already done at official document way, but still there were error like this, of course like this
https://brocha.in/testnet/sei-testnet-2/installation

but how can i fix it? 

please help

**Screenshots**

<img width="1496" alt="image" src="https://github.com/sei-protocol/sei-chain/assets/49632565/b57f8ca3-2560-4d92-bd1b-d55e6b5aea83">

**Additional context**

**Comment by BrandonWeng** [comment]
There was a migration from 2.0.48beta -> 3.0.0 -> 3.0.1. 

If you're running into this it's most likely because you're doing a hard upgrade from an existing data folder that was initialized with an older version. You can switch back to the older version and be prompted for an upgrade, or it would be easiest to just   start fresh with 3.0.1 

`rm -rf ~/.sei/data/ && mkdir ~/.sei/data/ && echo "{}" > ~/.sei/data/priv_validator_state.json`

**Comment by victor0807** [comment]
> 
thank you for reply, but i still have a problem with same issue. 
i already follow your guide, remove .sei/data and set priv_validator.state.json {} and i follow https://brocha.in/testnet/sei-testnet-2/installation 

but still have same problem... 

i will do switch back old version 2.0.48beta_branch and reply again. 

really thank you. come back soon

**Comment by BrandonWeng** [comment]
Hey @victor0807 apologies, the issue might actually be related to statesync configs not being configured properly too. This might indicate that you're missing a trust height or trust hash 

https://docs.sei.io/full-node/run-a-sei-node/join-a-network#configurations

**Comment by victor0807** [comment]
thank you @BrandonWeng , i will try that you guide me.

**Comment by victor0807** [comment]
Hello, @BrandonWeng . I really thank you for your helping. but i want to show you my server status. because i want to be confirmed by you. 

<img width="1481" alt="image" src="https://github.com/sei-protocol/sei-chain/assets/49632565/739a80bd-637f-4de1-87aa-4d6af0bef713">

i set my node by state_sync. but i need to check more. Could I ask you to check more? because i want to run fullnode gracefully, because our business service depend on deposit and withdraw. sorry for taking up your time. 

1. it look syncing well, but fetching snapshot chunk height is still 1242000, is it normal? current blockheight is 12456485. 

2. this is first time that i run cosmos node, what is cosmovisor? Is the sdk absolutely necessary? 

3. if i restart statesync optioned node, node look start with "trust-height"  block. that mean when i restart node, i need to update trust-height and trust-hash? 

I really apprieciate to you
Victor

**Comment by BrandonWeng** [comment]
In this case, it's restarting, you need to wait for the snapshot chunks to be fully applied and it will start catching up to the latest height. 

Note, this repo is more for tracking technical issues, if you're having issues with running a full node you can get quicker response on the discord server: https://discord.gg/sei
