### ISSUE TITLE
[Question] Is there any persistant peers ?

### ISSUE THREAD

**Issue by victor0807** [sei-protocol/sei-chain#866]
**Seid version**
3.0.3

**Chain ID**
atlantic-2

hello, @BrandonWeng. I need help about peers.
I already setting fullnode, of course running node on ec2 also making some api to track transfer data.
i have a problem about sync block data. block height changes very fast as you know. and my node can't follow block sync.
if i want to follow block height recently, should i make ec2 on europe area? i'm working in south korea. so my region is Asia. 
Please give me some good ideas. 

and one more question. i set up new ec2 to follow block height. Is node need to time to index block height? i saw log that request light node block recently after that , seid repeat add new peer and connect peer and failed to handshake with peer. Should i need to wait for long time when i run new node ?

* could you give persistant peer list? 

please understand my poor english. 
thank you

**Comment by philipsu522** [comment]
https://docs.sei.io/full-node/run-a-sei-node/join-a-network
