### ISSUE TITLE
[Question] Running State Sync Node can't find block

### ISSUE THREAD

**Issue by victor0807** [sei-protocol/sei-chain#870]
**Seid version**
3.0.3

**Chain ID**
atlantic-2

hello, i'm victor from south korea. 

i'm still have 2 problem with running sei fullnode. i will show picture what problem is 

Problem 1. I set up new node with my MacBook pro max(m2 1TB ssd, 64GB memory). but An error like the picture below occurred.
before when i run a node, it doesn't happen on aws ec2.

<img width="1752" alt="run seid" src="https://github.com/sei-protocol/sei-chain/assets/49632565/623094e4-7a5f-4a84-9d98-d9e6de3b7294">
1. i followed perfectly https://brocha.in/testnet/sei-testnet-2/state-sync 
and i also add more peers at config persistant-peers  and you can see some peers were added.

<img width="1707" alt="second" src="https://github.com/sei-protocol/sei-chain/assets/49632565/0dced397-7a6a-4246-bb45-a4918da8c2ff">
2. it looks well now

<img width="1817" alt="third" src="https://github.com/sei-protocol/sei-chain/assets/49632565/2ffd53e7-d67e-43b2-a303-f3038ad833b0">
3. it looks well too, received light block response with peers

<img width="1696" alt="four" src="https://github.com/sei-protocol/sei-chain/assets/49632565/5f29d605-dc5c-4e64-bf16-70f3c91311af">
4. you can see red line that i think it happen when it indexing block height. <- just my thinking 
could you give me answer how to deal with this problem ? After this error (client failed respond, deemed unreliable ) , my node repeat infinitely like picture 5.

5. repeat connect peer and disconnect peer again, again, again. I thought it might be indexing block height job, but it does not. 
<img width="1784" alt="five" src="https://github.com/sei-protocol/sei-chain/assets/49632565/44782cc8-fb24-4a46-84de-d939261d4501">

Problem 2
additionally, i also running sei atlantic-2 node  on aws ec2(region is ASIA). but it syncing very slowly. can not catch up recently block height. so i change high nvme ebs. it looks well but can not catch up block height, could you recommend what should i do?

I think the development team will be the most accurate, so I ask questions every time. Thank you very much. Also please understand my poor english.

**Comment by philipsu522** [comment]
@victor0807  have you checked out https://docs.sei.io/full-node/run-a-sei-node yet? Most folks are able to get things working with those instructions. If you're still having issues, please follow up in our Discord server (https://discord.gg/sei).  Github issues might not be the best place to do this. Github issues are more relevant for actual bugs in the code rather than debugging help.

**Comment by victor0807** [comment]
@philipsu522 hey, have you check discord channel? there were no channel for develop or infra. I am also Backend Developer   . i don't want to deal with this issue. I also running fullnode on aws but it can not catch up block height recently. Additionally, there were problem again when i run fullnode macbook. Do you think I haven't run through the guide? I tried many time but there were unexpected problem. did you see my problem detailed?

**Comment by philipsu522** [comment]
Can you try using an older height for state syncing?

**Comment by victor0807** [comment]
> Can you try using an older height for state syncing? Try starting 50k block behinds current height

it mean that change trust-height and trust-hash before 50k and start db sync mode? 
i will reset all system and try again. 

thank you

**Comment by victor0807** [comment]
> Could you explain why seid daemon shutdown ?
> 
> <img alt="스크린샷 2023-06-13 오후 6 18 40" width="1364" src="https://user-images.githubusercontent.com/49632565/245422755-e8e26592-b818-4b5e-9a4c-06e1ba27f366.png"> <img alt="스크린샷 2023-06-13 오후 7 58 56" width="1473" src="https://user-images.githubusercontent.com/49632565/245453962-f0f045f5-9cbb-41ab-88bb-2cc6c0fd6efd.png">
> i think some block height make a error, when syncing. could you recommend me what should i do? my trust-period is 168h now

@philipsu522 @BrandonWeng
