### ISSUE TITLE
Could not found Sei-Chain dependencies

### ISSUE THREAD

**Issue by Timwood0x10** [sei-protocol/sei-chain#891]
Hi Sei-Chain team
I have the latest version of the sei-chain code, but I'm running into some issues with the` Go mod Tidy`. 

![image](https://github.com/sei-protocol/sei-chain/assets/121157680/90a61604-6e45-49fa-861c-ecdf63fa2d68)

the code git log info
![image](https://github.com/sei-protocol/sei-chain/assets/121157680/b64a0b4f-ac6d-4ab3-9653-1ed772007b1a)

**Comment by BrandonWeng** [comment]
hey, @Timwood0x10 can you double-check? It seems to be working for me 

`go mod verify`  may also help `go clean -cache` 

![image](https://github.com/sei-protocol/sei-chain/assets/18161326/a86d26af-b362-4ca8-b2e7-1b1b484c0bdf)

![image](https://github.com/sei-protocol/sei-chain/assets/18161326/3602c891-1d9e-4529-8570-fe26c6f776a6)
