### ISSUE TITLE
[BUG] script issues

### ISSUE THREAD

**Issue by YiJingGuo** [sei-protocol/sei-chain#892]
**Seid version**
name: sei
server_name: <appd>
version: 3.0.1-65-g624eed31
commit: 624eed31cb10d36c6d72de44d7e3ad055ab40a3c
build_tags: netgo ledger,
go: go version go1.20.5 linux/amd64

I encountered the following error when executing the startup script command `./scripts/initialize_local_chain.sh`, based on the information provided in the link `https://docs.sei.io/develop/developer-tools/local-sei-node`.

error:
`sed: can't read s/mode = "full"/mode = "validator"/g: No such file or directory`

I resolved this issue by modifying the script from 
`sed -i '' 's/mode = "full"/mode = "validator"/g' $HOME/.sei/config/config.toml`
to 
`sed -i 's/mode = "full"/mode = "validator"/g' $HOME/.sei/config/config.toml`

After modifying the script and attempting to restart it, an error occurs.
error:
`panic: value from ParamSetPair is invalid: error: invalid start date format use yyyy-mm-dd: parsing time "" as "2006-01-02": cannot parse "" as "2006"`
The solution is to manually modify the content of end_date and start_date in `root/.sei/config/genesis.json` to make them consistent.
from
![image](https://github.com/sei-protocol/sei-chain/assets/45255185/932096b2-1dfb-4fa5-9aea-4617877b0b44)
to
![image](https://github.com/sei-protocol/sei-chain/assets/45255185/0567b725-28fa-419d-ab5b-5f8e0bd69228)

To start the chain, use the following command:
`seid start --trace --chain-id sei-chain`

success

This script can be improved according to the above.

**Comment by philipsu522** [comment]
@YiJingGuo you need to follow instructions [here](https://testnet-explorer.brocha.in/sei%20atlantic%202/statesync) to statesync, since the genesis file was created with a different seid version
