### ISSUE TITLE
[BUG] Rust version issue

### ISSUE THREAD

**Issue by YiJingGuo** [sei-protocol/sei-chain#895]
**Seid version**
name: sei
server_name: <appd>
version: 3.0.1-65-g624eed31
commit: 624eed31cb10d36c6d72de44d7e3ad055ab40a3c
build_tags: netgo ledger,
go: go version go1.20.5 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6
- github.com/CosmWasm/wasmd@v0.27.0 => github.com/sei-protocol/sei-wasmd@v0.0.2

An error occurred when running the `./deploy.sh` command following the tutorial at https://docs.sei.io/develop/get-started/counter-smart-contract-tutorial.Afterwards, I manually entered the commands from the script.
```
seid tx wasm store /home/y/sei-chain/counter/artifacts/counter.wasm -y --from=admin --chain-id=sei-chain --gas=20000000 --fees=10000000usei --broadcast-mode=block
```
error:
```
code: 2
codespace: wasm
data: ""
events:
.....
gas_used: "10889300"
gas_wanted: "20000000"
height: "17667"
info: ""
logs: []
raw_log: ".....  /sei-chain/app/app.go:963\nfailed
  to execute message; message index: 0: Error calling the VM: Error during static
  Wasm validation: Wasm bytecode could not be deserialized. Deserialization error:
  \"Unknown opcode 192\": create wasm contract failed"
......

```
This problem, I looked up for a long time, and finally found on the `https://substrate.stackexchange.com/questions/7881/error-loading-of-original-wasm-failed`  that it may be a problem with the Rust version, and switched the rust version from **1.70 to 1.69**.

After recompiling and storing the contract, the returned content is as follows.
```
code: 0
codespace: ""
data: 0A240A1E2F636F736D7761736D2E7761736D2E76312E4D736753746F7265436F646512020801
......
```

Then I instantiate the contract using the following command.
```
seid tx wasm instantiate 1 '{"count": 0}' --from admin --broadcast-mode=block --label "counter" --chain-id sei-chain --gas=30000000 --fees=300000usei --admin sei1rtxhnsul9205wft5nfhnj4hq8wk868ul4fljhj -y 
```
After that, the contract address is returned
```
code: 0
codespace: ""
....
- events:
  - attributes:
    - key: _contract_address
      value: sei14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sh9m79m
    - key: code_id
      value: "1"
    type: instantiate
.....
```
Then I tested `increment.sh` script and it returned to normal.
```
New count:  1
New count:  2
```

I hope the above can help you.

**Comment by BrandonWeng** [comment]
Thanks! We just updated the requirements for the Rust version, appreciate it
