### ISSUE TITLE
[Question] Questions about blockchain node operation

### ISSUE THREAD

**Issue by victor0807** [sei-protocol/sei-chain#919]
Hello, I'm victor 

Thank you for helping before. I have a issue about maintain Sei Blockchain. 

In non-European regions, it is difficult to keep blocks synchronized. It is impossible to perform block synchronization in Asia. When the mainnet is launched, will you provide peers in Asia? And the current Sei blockchain is difficult to maintain using cloud infrastructure. This is because disk IO usage is large. Or Could I use Bare Metal Service? 

In my case, i running 2 fullnode in aws EC2. AWS EBS has difficulty accommodating Sei blockchain's IO utilization. 
How could i solve this problem? Also Could you give me some advice to run Pruning options? 

pruning = "custom"

pruning-keep-recent = "3000"  <-- it look like  300 sec , 
pruning-keep-every = "0" <- i can't understand 
pruning-interval = "10" <- what's mean of interval ? it told me every each 10 block  node will pruning? 

thank you

**Comment by philipsu522** [comment]
hey @victor0807 , when the node does pruning, depending on how fast your disk is, it ends up potentially causing spikes in IO, and if tuned in correctly the IO could end up slowing your node.
Let's try changing "pruning=default", since that will take snapshots less frequently.
Another thing you could do is to raid your disks so you can parallelize disk io. I'll keep this open until you report back

**Comment by victor0807** [comment]
> EC2 is a virtualized disk, so IO is relatively slow. So I purchased an m.2 disk and am testing it. Additionally, I try to synchronize newly installed nodes by changing to AWS Europe area, but I can't connect well because I don't have enough peers.

I'm an employee of the cryptocurrency exchange. Synchronization of nodes is paramount to maintain stable service. However, despite numerous tests, synchronization in Asia was impossible even with EC2 or Bare Metal.

I'll try to find a way more. Oh, by the way, can you give me a rough idea of the release schedule of the mainnet?

thank you

**Comment by victor0807** [comment]
<img width="1615" alt="스크린샷 2023-06-28 오후 5 07 36" src="https://github.com/sei-protocol/sei-chain/assets/49632565/68a6b0b4-bc47-4c0f-8b09-1d06a77e51da">

A new node is being installed in the German region. This is what happens every time you install a new node. The following happens when state-syncing. Usually, if the peer is connected after the error, the fetch block and apply block processes are performed. But the peer doesn't connect well. 

<img width="1987" alt="스크린샷 2023-06-28 오후 5 10 41" src="https://github.com/sei-protocol/sei-chain/assets/49632565/a5288277-66ea-48c4-914d-24bac9610dab">
After that, the 'send message fail' issue repeats infinitely like the contents of the second picture. Have you ever been through this situation?

**Comment by victor0807** [comment]
I found why state sync working bad, because peers were so small. I restart node more than 500 times and finally it connected with peers. It could be solve when mainnet launch.

**Comment by philipsu522** [comment]
Thanks @victor0807 , closing
