### ISSUE TITLE
[FEATURE] Statesync snapshot directory configuration

### ISSUE THREAD

**Issue by nullmames** [sei-protocol/sei-chain#925]
It would be advantageous for some operators to be able set the directory for snapshots in the `app.toml`. Our specific use case for this is to easily configure the app to create snapshots on a ramdrive. 

It would be possible to achieve this by using a symlink, however the configuration flag would reduce configuration complexity.

**Comment by yzang2019** [comment]
We will work on it soon

**Comment by yzang2019** [comment]
Implemented in https://github.com/sei-protocol/sei-chain/pull/944/

**Comment by philipsu522** [comment]
Will roll out in next upgrade (3.0.6)
