### ISSUE TITLE
[FEATURE] Metadata feature for tokenfactory module

### ISSUE THREAD

**Issue by hoomp3** [sei-protocol/sei-chain#932]
# Problem
There is no way to set any metadata for tokens created using the token factory module with the method found here - https://github.com/sei-protocol/sei-cosmwasm/tree/main/packages/sei-cosmwasm#tokenfactory. The CreateDenom message in sei_cosmwasm only takes a subdenom as an argument.

As a result, querying for the metadata or token info of a custom native token created by the token factory module returns the following:

![photo_2023-06-26 15 15 22](https://github.com/sei-protocol/sei-chain/assets/93625260/4c1198f5-431b-46d2-bb48-deecb238a259)

# Solution
Users should be able to specify desired metadata when creating native tokens using the token factory. Users should also be able to specify the intended token decimals in addition to the other token metadata (ex: The smallest token amount of ATOM is 10e-6 so this would be 6. The smallest ETH is 10e-18 so this would be 18). This improves the UX of integrating with native tokens since users will be able to rely on getting the metadata from the chain and allows for different custom native tokens to have different token precision.

**Comment by hoomp3** [comment]
Any update on this? Hoping it will be part of mainnet.

**Comment by BrandonWeng** [comment]
@hoomp3 apologies for the delay, there's a PR here for the change. We should be able to get it merged sometime this weekend. 

https://github.com/sei-protocol/sei-chain/pull/963

**Comment by hoomp3** [comment]
@BrandonWeng okay thanks! when should I expect this update to be reflected here - https://github.com/sei-protocol/sei-cosmwasm?

**Comment by BrandonWeng** [comment]
> @BrandonWeng okay thanks! when should I expect this update to be reflected here - https://github.com/sei-protocol/sei-cosmwasm?

We'll either get it this weekend or early next week!

**Comment by hoomp3** [comment]
@BrandonWeng sweet, looking forward to it!

**Comment by hoomp3** [comment]
@BrandonWeng No worries, thanks for letting me know.

**Comment by BrandonWeng** [comment]
https://github.com/sei-protocol/sei-chain/pull/989

**Comment by BrandonWeng** [comment]
@hoomp3 it should've just been deployed to atlantic-2 during today's upgrade :)
