### ISSUE TITLE
TPS vs OPS

### ISSUE THREAD

**Issue by duongnq2798** [sei-protocol/sei-chain#954]
### Search before asking

- [X] I searched in the [issues](https://github.com/sei-protocol/sei-chain/issues) and found nothing similar.

### Motivation

Could you please explain the difference between TPS and OPS? I noticed that Sei's transactional throughput is 20,000 operations per second.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by philipsu522** [comment]
@duongnq2798 TPS refers to number of transactions, while OPS refers to operations/orders. There could be multiple operations/orders per transaction

**Comment by duongnq2798** [comment]
Can you provide a specific figure/estimate of the SEI TPS. Or how to calculate from OPS to TPS
