### ISSUE TITLE
[BUG] Can make transactions but, transactions are not getting synced with local blockchain

### ISSUE THREAD

**Issue by lhtpavankumar** [sei-protocol/sei-chain#957]
**Seid version**
name: sei
server_name: <appd>
version: 3.0.1-108-g3ffd72ad
commit: 3ffd72adce56b7b430f737f1f403bcbbc0531b27
build_tags: netgo ledger,
go: go version go1.18.1 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6
- github.com/CosmWasm/wasmd@v0.27.0 => github.com/sei-protocol/sei-wasmd@v0.0.2

**Chain ID**
sei-chain

**Describe the bug**

- I have cloned sei-chain then
- initialize a local node using scripts of initialize_local_chain.sh
- then I haved copied and placed seid binary into /usr/bin
- there, i started executing seid cli commands
- the problem is, i can make transaction but chain state is not syncing

Error shows as 
![image](https://github.com/sei-protocol/sei-chain/assets/91463083/13ebd68f-b769-44e7-8ab5-ddebc70166ff)

**Comment by alexanderbez** [comment]
A few Qs:

- What mode did you broadcast the tx with? `sync` or `async`? Or did you not specify?
- Is the node you broadcasted against caught up to the tip of the chain? Or was it still syncing?

**Comment by lhtpavankumar** [comment]
What mode did you broadcast the tx with? sync or async? Or did you not specify?
I just run the `scripts/initialize_local_chain.sh`

Is the node you broadcasted against caught up to the tip of the chain? Or was it still syncing?
I was running a local blockchain with in my system i believe using `scripts/initialize_local_chain.sh`

**Comment by yzang2019** [comment]
@lhtpavankumar what exact command did you execute for this transaction?

**Comment by yzang2019** [comment]
@lhtpavankumar You need to add -b block -y to your command, for example in this case:
`seid tx bank send sei1pn5th7kylq47nyut0p5lcazr50rrm8rkavddeh sei1cgtvr45yyyx44kmtaq27srqru78nwcf93qu78s 1usei --chain-id sei-chain -b block `
