### ISSUE TITLE
Using local nodes to build some problems

### ISSUE THREAD

**Issue by onebyoneby** [sei-protocol/sei-chain#985]
I use the scripts/initialize_local_chain.sh script for local setup.
1. At the current node height of 1/100, I cannot query the wallet balance using the command (seid q bank balances sei183xtf2wmcah9fh5kpdr47wlspv3w47c0lgvwvf --chain-id sei-chain). Is it a problem with my order or the node needs to be highly synchronized
2. How long does it take for node height synchronization? Will it take a month at the current speed?
3. I use a script built locally. When my computer restarts, how do I run the local node? I can’t find any relevant hints in the script?
![image](https://github.com/sei-protocol/sei-chain/assets/50565415/e89ec495-2451-4751-85a1-c28c215e8255)
![image](https://github.com/sei-protocol/sei-chain/assets/50565415/bc4ed5e9-ded8-41e6-b709-ee6a14ee011e)
![image](https://github.com/sei-protocol/sei-chain/assets/50565415/e03b1972-ff54-44af-b7d1-5158de45253c)

**Comment by philipsu522** [comment]
@onebyoneby running `scripts/initialize_local_chain.sh` is the correct way to run a chain locally, and it should sync immediately since it is a 1 node chain. This will not sync to any external chain. You should execute `seid keys list` to verify that the address exists, then you can query the bank balance.

**Comment by onebyoneby** [comment]
> @onebyoneby running `scripts/initialize_local_chain.sh` is the correct way to run a chain locally, and it should sync immediately since it is a 1 node chain. This will not sync to any external chain. You should execute `seid keys list` to verify that the address exists, then you can query the bank balance.

But how can I restart my local node if it drops.

**Comment by onebyoneby** [comment]
and I followed the document and his contract address was empty
![image](https://github.com/sei-protocol/sei-chain/assets/50565415/96ca3a7e-7836-4277-9c9e-2082c7ddcec5)

**Comment by philipsu522** [comment]
You can just run seid start
