### ISSUE TITLE
 local node is synchronized

### ISSUE THREAD

**Issue by onebyoneby** [sei-protocol/sei-chain#999]
![image](https://github.com/sei-protocol/sei-chain/assets/50565415/75d277cd-264a-4be9-a21f-04b3b3d7dead)
When the local node is synchronized to the height of 216000, the node will crash. Is there any way to keep the local node running without crashing?

**Comment by philipsu522** [comment]
Can you give more context? which chain are you syncing on?

**Comment by onebyoneby** [comment]
> local node

local node，use script to initialize_ Local_ Chain

**Comment by Jackwumingjie** [comment]
@philipsu522 I have met the issue, the node maybe need the persistent-peers or seeds and other seeds. Can you provide the related seeds?

**Comment by ratneshpatil-rp** [comment]
hi @Jackwumingjie did you got peers list?

**Comment by philipsu522** [comment]
You can find peers here: https://docs.sei.io/develop/resources#statesync-rpcs
